### ISSUE TITLE
Black Border at bottom on some Naomi games

### ISSUE THREAD

**Issue by filevans** [flyinghead/flycast#904] opened 2023-02-01 13:53 UTC
hello, 
some games have a black border at the bottom, street fighter zero 3 upper is one, and i think virtua tennis 2 was another, i've encountered it on a few games, it only affects the naomi versions and never the Dreamcast version and reportedly doesn't happen on standalone flycast. the top and bottom black border is very uneven so overscan option can't be used as it then cuts the top off

![image](https://user-images.githubusercontent.com/14978933/216062851-51038985-299d-49e0-a3dd-e373adf34637.png)

if this can't be fixed easily, could a screen centralising option up/down could be added ? 

thank you for listening

**Comment by flyinghead** [comment] 2023-02-01 14:52
Street Fighter Zero 3 upper is not a Naomi game.
Virtua Tennis 2 console and naomi versions don't have any black border, 

Duplicate of #594

**Closed by flyinghead** 2023-02-01 14:52 UTC

**Comment by filevans** [comment] 2023-02-01 15:11
Street Fighter Zero 3 Upper **IS a Naomi game**

and has uneven black borders

https://en.wikipedia.org/wiki/Street_Fighter_Alpha_3

"Street Fighter Zero 3 was re-released for the arcade in Japan in [2001](https://en.wikipedia.org/wiki/2001_in_video_gaming) under the title Street Fighter Zero 3 Upper (officially promoted as Street Fighter Zero 3↑). The game was released for the Dreamcast-based [NAOMI](https://en.wikipedia.org/wiki/Sega_Naomi) hardware (rather than the original game's CP System II hardware)"

plus I have it and am running it on Naomi

**Comment by filevans** [comment] 2023-02-01 15:16
ok you're clearly an idi*t as you don't even know which games are Naomi or not

**Comment by flyinghead** [comment] 2023-02-01 15:20
I made a mistake but insults will get you nowhere

**Comment by jezabe** [comment] 2023-02-01 15:39
> I made a mistake but insults will get you nowhere

learn to listen instead of replying arrogantly, user filevans was polite in his request, you weren't, you were the one insulting with your arrogant response, you dismissed it and immediately closed the issue without even listening, also you don't even know which games are for naomi? maybe you should find out

**Comment by Taiyaki777** [comment] 2024-11-19 18:58
Any chance this is on some to do list? It's the best version of a pretty popular title and the flycast core in Retroarch is still forcing black borders on it while the standalone is not. Would be great to see this fixed.

**Comment by flyinghead** [comment] 2024-11-19 20:18
Flycast standalone:
![image](https://github.com/user-attachments/assets/847589e5-99c9-4096-9a61-db4efaeb3c3d)

RetroArch:
![image](https://github.com/user-attachments/assets/7fa6aa17-f804-466e-988b-1f165de8d5c2)

**Comment by Taiyaki777** [comment] 2024-11-20 03:51
My bad. I checked and Demul does the same. 

Is this a dump issue or was the game always this way? I remember this game back in the day and never recall it slightly squishing the sprites. In my memories it was always full screen. The vertical squishing is reminiscent of the Capcom Saturn ports.

**Comment by Taiyaki777** [comment] 2024-11-20 03:57
For what it's worth I looked it up and managed to find a video of the game running on the original hardware on Youtube and this was present on that as well. So my apologies.

https://www.youtube.com/watch?v=Hprq1_cH25w
