### ISSUE TITLE
Monkey Ball (Naomi): Black screen during gameplay

### ISSUE THREAD

**Issue by trstmp** [flyinghead/flycast#116] opened 2020-09-22 23:42 UTC
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Windows x64

Github hash: a9f1a89

Hardware: i5-6600K, GTX 1060

**_Description of the Issue_**

In Monkey Ball (Naomi), right before being able to control the character, the screen goes black except for the UI graphics.

![monkeyball](https://user-images.githubusercontent.com/55026251/93947993-85551700-fd3d-11ea-850e-d374715c8de0.png)

Edit: After a bit of testing it seems 2e9238d (2020-05-11T14:21:09) is the first version that exhibits this issue. The game works fine on previous versions.

Edit 2: All versions starting with 2e9238d also have an issue with F355 Challenge (Dreamcast) where the game freezes when starting a race.

**Comment by flyinghead** [comment] 2020-10-10 16:43
I can reproduce it with Open GL in per-pixel mode only. It seems to be linked to clipping so disabling clipping does help.

Thanks for figuring out which commit is the culprit.

**Comment by flyinghead** [comment] 2020-10-10 17:24
I can't reproduce the F355 issue. Can you give me more details?

**Comment by flyinghead** [comment] 2020-10-10 19:58
black screen should be fixed

**Comment by trstmp** [comment] 2020-10-10 21:04
Not sure what was going on with F355 Challenge but both games are fixed now. Thank you.

**Closed** 2020-10-24 14:08 UTC
Labels: bug
