### ISSUE TITLE
NBA 2K2 freezes when a game ends

### ISSUE THREAD

**Issue by mfigueirido** [flyinghead/flycast#1667] opened 2024-10-07 20:32 UTC
Platform / OS / Hardware: 
Windows 11 x64

Github hash: 
56fe3b9c9d0ce44fb54fdf28cbcd1a984346fa30

Hardware: 
AMD Ryzen 2600, Radeon RX 570, 16GB RAM

**_Description of the Issue_**

Sometimes the emulator freezes when you finish a game in NBA 2K2 (USA region, GDI).
Here is a save state. To reproduce just select "exit game":
[NBA 2K2 save state.zip](https://github.com/user-attachments/files/17284184/NBA.2K2.save.state.zip)

**_Debugging Steps Tested_**

This happens in both standalone and Libretro.

**_Screenshots_**

![imaxe](https://github.com/user-attachments/assets/97ed1613-020a-4062-89dd-895cc341a64d)
![imaxe](https://github.com/user-attachments/assets/b08145f2-cbb2-4016-8f17-1f4b286c1a5e)

**Comment by flyinghead** [comment] 2024-10-07 22:04
duplicate of  #1481

**Closed by flyinghead** 2024-10-07 22:04 UTC
Labels: bug
