### ISSUE TITLE
Gaelco, Cave1000, and Hikaru Support

### ISSUE THREAD

**Issue by Arcadeguy781** [flyinghead/flycast#862] opened 2023-01-10 23:57 UTC
I've been enjoying this emulator so far and I was hoping for more variants such as Hikaru, Gaelco PVR, and Cave CV1000 support in the future.

**Comment by flyinghead** [comment] 2023-01-11 05:36
Duplicate of #110

**Closed by flyinghead** 2023-01-11 05:36 UTC
Labels: enhancement
