### ISSUE TITLE
Please support the newly dumped Project Justice / Moero! Justice Gakuen (Rev B)

### ISSUE THREAD

**Issue by crashGG** [flyinghead/flycast#725] opened 2022-09-01 08:39 UTC
In the late few days, "pjustic" has become Project Justice / Moero! Justice Gakuen (Rev B), and Project Justice / Moero! Justice Gakuen (Rev A) was renamed "pjustica"

**Comment by flyinghead** [comment] 2022-09-01 08:56
duplicate of #716

**Closed by flyinghead** 2022-09-01 08:56 UTC
Labels: enhancement
