### ISSUE TITLE
Select the mouse index in the control settings?

### ISSUE THREAD

**Issue by fpushin** [flyinghead/flycast#138] opened 2020-12-06 13:25 UTC
Hello everyone. I'd like to thank everyone for your excellent job on the windows standalone versions i'm using on my cab!

Is it possible to add an option to select the mouse index in the control settings so we can use 2 lightguns for two players games? I'm currently using aimtrak devices, who work pretty well for 1 player but they are sharing the same mouse pointer. I don't know if it's something easy to do but it who be awesome if i could get all my DC/naomi and atomiswave games running with Flycast, including 2 players lightgun games (demul is.. a bit old and imperfect).
Thank you for reading me, have a good day :-)

**Comment by flyinghead** [comment] 2020-12-06 14:28
Unfortunately this is not trivial. See https://discourse.libsdl.org/t/does-current-sdl-support-multiple-mice-for-mame/26012

**Comment by flyinghead** [comment] 2021-03-01 13:59
Multiple mice are now supported on Windows.

The mouse must be in capture mode (L-Alt+L-Ctrl), then multiple mice/lightguns can be used.

**Comment by fpushin** [comment] 2021-03-01 21:53
Great news!! On my way to test this and give you a feedback. Thanks a lot for your work!!

**Comment by fpushin** [comment] 2021-03-04 20:56
> Multiple mice are now supported on Windows.
> 
> The mouse must be in capture mode (L-Alt+L-Ctrl), then multiple mice/lightguns can be used.

Hi, i've spent a couple hours to test some light gun games (games tested : house of the dead 2 and Confidential missions on DC). I'm actually using 2 aimtracks light guns and I also tried with two mice. I was using the release dated 03/01/2021 on a mini PC with Celeron J4125 with Intel HD 600 graphics on Win10.

Here is my feedback : 

-1 player with capture mode work pretty well but the cursor is stuck between the left side and the middle of the screen (it doesn't happen every time but pretty often). When I disable the capture mode, the mouse cursor work well.

-When I enable two lightguns or mice and then activate the capture mode, both cursors disapear as soon as i move the second player's cursor and the two devices seems disabled, including buttons (it happens every time)

I don't know if you already know  this issues and if there's a fix for this :-) If you need more tests, i'm your man!

Thanks again for your awesome work.

PS : It would be great if we could have a option to auto enable the capture mode on a game launch when lightguns are selected ;-)
PS2 : sorry for my poor english level!

**Comment by flyinghead** [comment] 2021-03-05 10:24
I haven't been able to reproduce the problem on my end.

Make sure to set the Maple port for each used RAW mouse. It's tricky to figure out which mouse is which since their name is cryptic but it's possible with some trial and error. When switching to capture mode, the default (SDL) mouse is inactive and only the RAW mice work. When switching back to normal mouse mode from capture, it's the exact opposite: only the default SDL mouse work, and the RAW mice don't.

Also, when you talk about the mouse "cursor", I assume you mean the lightgun crosshairs. When in capture mode, the Windows mouse pointer (arrow) will disappear. The crosshairs on the other hand are always visible (if enabled). I'm not sure what you mean by "both cursors disappear" since they should always be visible (unless moved off-screen).

It could help if you posted some screenshots of your Input settings, as well as what you see on screen. Or perhaps a video.

PS: your English is fine!

**Comment by flyinghead** [comment] 2021-03-05 10:26
My settings:
![image](https://user-images.githubusercontent.com/16261910/110102744-70c58200-7da5-11eb-9019-c164b109938a.png)

House of the Dead with both mice working:
![image](https://user-images.githubusercontent.com/16261910/110102841-8c308d00-7da5-11eb-89a3-940348838882.png)

**Comment by fpushin** [comment] 2021-03-10 19:34
Hi, 
I'm back with some evidence of my problem. You can find in attachement of the message a screenshot of my controls config and and short video of my problem with two aimtrak gun : 
When i launch the game my mouse SDL work fine, then when I switch to capture mode my fiirst gun reacts well but as soon as I point the second lightgun both crosshairs disapear (You can briefly see the red crosshair blinking at the side of the screen then disapearing while I was moving the guns.). When i disable capture mode my mouse pointer comes back and is correctly controlled by both of my guns.


Here's what I've tried  : 
-enabling capture mode later in the game
-disabling every other controllers
-enabling the second lightgun later in game
-trying another game

None worked of course :-)


![Capture](https://user-images.githubusercontent.com/75571517/110685172-4a0cae80-81de-11eb-9526-0d74600626e6.JPG)



https://user-images.githubusercontent.com/75571517/110685471-99eb7580-81de-11eb-8d86-f13f7f967998.mp4

Thank you in advance your efforts :)

**Comment by fpushin** [comment] 2021-03-12 20:07
Hi, i made a few tests to try recording my issues with two mice. Unfortunatly, as soon as I launch the video capture, the second crosshair disapear... (I tried with fraps or the xbox app integrated with win10). So all I can do for now is discribing my problem the best I can...

When I enable the capture mode, both crosshairs work well but it'll disapear when :
-I'm moving the second mouse during a loading screen
-when I use a mouse button on the second mouse (ie : right click to reload).

I'll try to record a video with my phone, it won't be easy to record and move the mice :-)

**Comment by flyinghead** [comment] 2021-03-13 08:04
Thank you for these additional details. Don't worry about recording a video if it's not possible.

I'll try to reproduce these issues on my end and fix them accordingly. The only problem might be if aimtrak guns act differently than mice since I don't have any to test with.

**Comment by flyinghead** [comment] 2021-03-15 15:07
When you switch to capture mode, both mice are put in relative mode. This means that Flycast only receives relative mouse movements, and has to keep track of them to determine the absolute position of each mouse.

When you move a mouse during a loading screen, the crosshairs' position isn't updated on the screen because the game is loading. There's no limit to the mouse coordinates currently so it may go way outside of the window/screen. I'll probably add a limit to avoid that, still allowing to go off-screen if needed (non-assisted reload).

As for the second issue with reload, I haven't been able to reproduce it. I bound the reload button to both mice right button and it worked fine. Are you using two actual mice or mixing with a different device? It could have something to do with binding if the devices are different, or not bound in the same way.

**Comment by fpushin** [comment] 2021-03-15 19:39
Hi,

I've seen your message so I tried your last release to give you a feed back. Lots of good things to say :-)

To begin with, I've made my tests with HOTD2 (on DC) only. I'll test other games and platforms later.

-Two players with RAW mice now works great. No loss of crosshairs, no bugs so far. Sensivity seems a bit high but I assume this is not a major problem :-)

Now, with two lightguns :

-There's a major improvement : both gun are working, but not at the same time. When I point both guns on the screen, both crosshairs disapear and the buttons binded on the gun (shoot, reload or start) don't respond. And I soon as I drop one gun the other start working normally again. This is the only big issue I had.

-another little problem : ths crosshairs sensivity is much higher than the sensivity in SDL mouse. It make the guns not calibrated. I assume this is because of the capture mode. I don't know if it's easy to get the same sensivity as the windows' mouse to keep guns calibrated, but it'd be great :-)

Thanks again for all your work, I'll keep doing some tests to give you my feedbacks.

**Comment by ldolse** [comment] 2021-04-07 15:09
Exciting to see the updates to get Lightguns working, thanks for all the efforts!  

I've tested this with the [Sinden lightgun](https://www.sindenlightgun.com), I was able to get Flycast to recognise two gun pointers with capture mode enabled, that said several issues:

Single Gun:
- Calibration is way off, the crosshair in capture mode is nowhere near where the gun is aimed, and seems to shift around a lot - without capture mode the mouse pointer and the gun are perfectly aligned
- I couldn't get off-screen fire to reload working reliably in capture mode - occasionally I could get it to reload by firing at the very edge of the screen, but normal behaviour is to point fully offscreen to reload - the Sinden driver tries to facilitate this, it's possible that made things worse, however it work well with the driver feature disabled either
- It doesn't recognise Sinden buttons assigned as keyboard keys - The Sinden driver represents the buttons as either a mouse or keyboard, flycast seems to only recognise those assigned as mouse buttons
- right mouse button (configured on the gun) didn't reliably work to reload in capture mode - it worked for a short while, afterwards only worked to skip cutscenes
- A single gun was recognised as player 2, the SDL mouse was configured as the first device by default - this caused a variety of flakiness that took me a while to understand as button presses from before capture mode was enabled were interpreted as a different controller.  
- I tried disabling the SDL mouse, but it disables it for the entire GUI, not just the emulator, that's prevented further testing for now - I'll try launching a game from the CLI later and I'll update if it makes a difference


Two guns:
-  It doesn't seem to recognise the buttons on both guns as two separate sets of buttons for each device, I was unable to get the buttons to be reliably recognised in capture mode with both guns plugged in - this was intermittent and either one gun or zero guns would work - sounds similar to the issue fpushin reported earlier.  


If any of this feedback makes sense to track for Sinden separately I'm happy to open a separate ticket to continue.

**Comment by flyinghead** [comment] 2021-04-13 14:00
Thanks for the feedback.

Here is some information to better understand what's going on:
When switching to capture mode, all mice (or mouse-like devices) are set to relative mode. This means that flycast only receives relative mouse motion events. So it calculates the absolute mouse position by keeping track of each relative motion. It also clamps the mouse coordinates to avoid it being too far off screen, since it's hard to put your mouse back on screen when it's at position -5000,-5000 😛 

This is true even when the mouse device sends absolute coordinates (which, I assume, the Sinden lightgun does?). So the coordinates clamping plus the relative motion can cause a big drift between computed and actual coordinates.

This is a limitation of SDL so not sure how to work around this.

Flycast only supports one keyboard, so all keyboard keys appear to come from the main keyboard, regardless of which physical device sent the event. So it's better to emulate mouse buttons instead. 
Note that there is a way to map keyboard keys to multiple players but the keys have to be different.

**Comment by ldolse** [comment] 2021-04-14 14:45
Thanks!  Yes, I believe the Sinden is using absolute coordinates - I believe the same is probably true for Aimtrak, which would align with fpushin's feedback.  When I saw you were using raw input I didn't realise that was still using SDL - I'll open a bug/feature upstream with them to see if absolute coordinates can be added as an option for raw input, looks like there are a few use cases for that anyway based on reading their bug tracker. 

That's good info on the keyboard mouse behaviour - I'll double check that again with that context.  Single keyboard shouldn't be a problem - I do have different keyboard keys assigned to some buttons on the guns to follow the Mame standard, anyway will double check that.

I did notice on [Libretro they have just checked in changes](https://github.com/libretro/mame2003-plus-libretro/issues/400) to support two Lightguns - in that case is Libretro handling the input for the flypast core so the SDL limitation is worked around that way?

**Comment by flyinghead** [comment] 2021-04-15 07:46
Flycast uses a patched version of SDL to support distinct mouse devices in capture mode. I'm afraid the solution to these issues would be to get rid of SDL and use the Raw Input API directly.

I believe RetroArch has a raw input driver already. The issue you mention is about wiring the mame core to be able to use the retroarch lightgun api. In this case, RA is handling the input so the Flycast core should work fine with multiple lightguns.

**Comment by flyinghead** [comment] 2021-04-29 17:25
I just pushed a new RawInput driver implementation that should overcome the previous limitations. It also allows multiple keyboards support.
There is now a setting to switch RawInput on and off. When on, the system mouse and keyboard are no longer used (except for the UI).

I committed this to the `fh/directx` branch although this has nothing to do with DirectX. But there are significant changes (and probably bugs) so it's safer to test it on a branch first. And you can also test the DX9 renderer if interested. You can find builds for this branch on the builds page.

I'd appreciate some feedback, even bad. It's still probably rough on the edge but will get better.

**Comment by fpushin** [comment] 2021-05-03 16:41
Hi, I'm on my way to test this release and give you a feeback asap :-)

**Comment by fpushin** [comment] 2021-05-03 21:20
Ok, just made some quick tests, I will go deeper if needed tomorrow after work : 

first try with one mouse only : 
the crosshair is not aligned with the bullets in the game but it works pretty well

second try with one aimtrak lightgun : 
as soon as i point the gun on screen the crosshair disapear.  
Could this have something to do with the fact that the aimtrak software reports the raw position as xxxx xxxx for the device when not pointed on the screen? because this should be the only difference with a normal mouse. I paste a screenshot from the soft wherre the gun is off screen. When point on screen it shows "normal" coordinates.

![screen aimtrak](https://user-images.githubusercontent.com/75571517/116934720-9ec02900-ac65-11eb-8ed7-a81b3a3001b0.jpg)

PS : thanks for the option that enables raw inputs at launch! BTW, the mouse cursor is no more hidden :p

Tell me if I can help with other tests :-)

**Comment by flyinghead** [comment] 2021-05-04 10:13
I just realized I hadn't tested absolute coordinates at all. Sorry about that.

I did some tests with a Wiimote + Dolphin bar (which does send absolute coordinates). It seems to work fine on my end after today's fix. Please give the latest build a try: https://github.com/flyinghead/flycast/commit/71fb024061fdcbfc272c25052727f0f8dd4c16ef

**Comment by fpushin** [comment] 2021-05-04 18:41
I made some tests, and it begins to smell really good!! :p 

tested on confidential mission and hotd2 on DC : 

The good news : 
-both lightguns react perfectly (no more loss of crosshairs), off screen reload and global reactivity are perfect

The "not so bad news" (I hope) : 
-crosshair is not not aligned with the gun. For example, when I point my gun on the left off the game screen (ratio 4/3), my crosshair is on the edge of the screen (16/9 screen). I guess there's something to do with the screen and game ratios (you're the magician, I'm only the tester :-)
-it still doesn't shoot on the crosshair, it shoots on the left of the crosshair
-a little one to finish : the mouse pointer is appearing in the middle of the crosshairs (for both player)

I hope this quick feedback will help to cross the finish line. The work u've done is awesome, thanks again!

**Comment by flyinghead** [comment] 2021-05-04 19:06
This is great news!

Some information:
- there's currently a limit on the crosshair coordinates so they don't get off screen by too much. This is useful for relative motion devices like regular mice. So if you point your lightgun to the left, the crosshair may appear "stuck" on the left side of the screen. It is still registered off screen and will still track your gun as soon as you point it back to the screen. So it shouldn't cause any problem.
- make sure you calibrate the gun in the game settings. Does it still shoot to the left after calibration?
- you still need to capture the mouse (Left CTRL+ALT) to hide the system mouse pointer.

**Comment by fpushin** [comment] 2021-05-04 20:31
I spent so many year playing gun games on old consoles and I didn't think about calibrating on an emulator, I'm a bit stupid :-) I tried and it worked perfectly! 

I'm still testing games and I might come back with some questions or requests.

Actually I've one question : Is there any way to configure a peripheral (a gun/mouse for example) with  different input default configuration for DC and arcade? My point is  that the reload button differs on dreamcast (there a reload input) and on Naomi (button 2 at least for the game I've tested). So We have to choose the default reload on "reload" for DC or button 2 for arcade games.  <--- I don't know if this sentence is understandable (it is, in my head at least). If not, i'll reformulate differently :)

I've seen we can make game profile, so it'll be my second option if we can't have a different profile for DC and arcade. I'l not sure this point deserve to spend time on it, I let u judge that :)

And last but not least : Is it possible to have an option to auto-enable capture mode when launching a game (at least for mouse/lightgun games? 

Thousands of thanks!!

**Comment by flyinghead** [comment] 2021-05-04 20:45
It's not currently possible to have per-game input mappings (or different mappings for dc and arcade), but it's one of the most requested features.

I'll see what I can do to auto-hide the mouse pointer.

**Comment by fpushin** [comment] 2021-05-21 07:41
Hi,
I'm back after somes tests with version e07977e. (I've tested the version 5f5d317 you've just released but the crosshair  and mouse are no more aligned with the guns, it moves to fast).

So, here are the DC games that worked great 👍 : 

Confidential Mission
DeathCrimson OX
Death Crimson 2 (a very bad game btw)
House of the Dead 2

I had some problems with Virtu Cop 2 : 
-the japan version works fine but mouse/lightgun not detected
-the american version included in Sega Smashpack volume 1 craches on launch


Naomi games : 
Confidential mission : OK
Death Crimson OX : OK
HOTD2 : OK
Lupin 3 the shooting : OK
The Maze of the kings : OK (but auto reload)

I'll continu my tests and will fill the list with other games. This is fun testing them, thanks to you !

**Comment by flyinghead** [comment] 2021-05-21 08:28
I'll have a look at what's wrong with the latest build (https://github.com/flyinghead/flycast/commit/5f5d31730c38a323a829d2961bb173bb7c342fd2).

Regarding Sega Smashpack vol.1, you need to force Windows CE (`Settings > Advanced > Force Windows CE`) since Virtua Cop 2 is a Windows CE game but the compilation itself isn't.

Thanks for your testing and feedback!

**Comment by flyinghead** [comment] 2021-05-21 08:59
I tested the latest build and it works fine here.
Note that I now automatically hide the system mouse pointer when running in full-screen.

Can you describe the issue more precisely? Does it also happen with RawInput off? Does it affect only lighguns, mice or both?

**Comment by fpushin** [comment] 2021-05-21 11:03
Well, my bad, i didn't copy the correct release in my folder!

With winCE forced : Virtucop2 work (Smashpack version) and lightguns are working. Is there any problem to let this option activated all the time?.

And thanks for hiding the mouse pointer, works great :-)

**Comment by flyinghead** [comment] 2021-05-21 11:15
Having Windows CE forced all the time can have a negative impact on performance with some non-Windows CE games. I wouldn't recommend it.

**Comment by bilu-git** [comment] 2021-08-22 13:14
When using the Flycast build included in Batocera 31 with a Dolphinbar the cursor area is limited to the top left, less than a quarter of the screen. I have been doing tests with the Hypseus Singe developer (faced the same issue) and finally found a way to fix it using the "manymouse" libraries https://github.com/DirtBagXon/hypseus-singe/commit/7928526229d264d73775710ec961b4f4abfaad03 .

This was tested on RPi4 and Batocera access to emulator properties is kinda limited unless they have hotkeys so I couldn't reach Flycast options.

**Comment by flyinghead** [comment] 2021-08-22 18:51
Thanks for the tip. Most of the development for this issue is targeted to the Windows platform. But the "manymouse" library could help bring these features to other platforms.

**Comment by flyinghead** [comment] 2022-06-23 20:24
Resolved

**Closed by flyinghead** 2022-06-23 20:24 UTC
Labels: enhancement, input

**Comment by nesper8** [comment] 2026-04-28 14:16
Hey can something similar can be implemented in X11/Linux?
IIRC this is currently impossible on Wayland because Wayland merges all mice/pointing device into a single cursor but I tested the new Ymir emulator's multi mouse functionality in X11 and found it possible in X11
