### ISSUE TITLE
MIRAI YOSOU STUDIO - Some textures and printout results are not displayed correctly

### ISSUE THREAD

**Issue by kihato** [flyinghead/flycast#1378] opened 2024-02-01 12:06 UTC
Windows11 / i7-10700F / GTX 1660 SUPER

Github hash: e286f98

Some textures are not displayed correctly. (I've tested all Graphics APIs, Sorting, but nothing works.)
![nittere](https://github.com/flyinghead/flycast/assets/14366233/856b8a28-8eb6-4cb6-9805-2d36ce55f68f)

Some of the printout results appear to be incorrect. (inside the red frame)

- I don't know what is printed in the red frame at the top on the actual machine, but I can't read it in this image.
- In the red frame in the middle, the letters are broken or overlap.
- In the last red frame on the right side, the character's face appears to be broken.

![MIRAI YOSOU STUDIO-results](https://github.com/flyinghead/flycast/assets/14366233/e0640e0e-ec4b-42a3-864f-efa1c052d3f4)

**Comment by TheCoolPup** [comment] 2024-02-01 12:14
This is a known bug, don’t know what the problem is yet

**Comment by flyinghead** [comment] 2024-02-01 17:36
Texture corruptions and most printing issues should be fixed in the latest `dev` build

**Comment by kihato** [comment] 2024-02-01 22:26
The textures are no longer corrupted and the printed output looks much better. Thanks!

Additional Information:
If you do not adjust the touch panel in test mode when starting up for the first time, you will only be able to move the cursor near the top right of the screen.

**Closed** 2024-02-03 17:25 UTC
Labels: bug
