### ISSUE TITLE
Problem with widescreen in Flycast

### ISSUE THREAD

**Issue by Branislav84** [flyinghead/flycast#757] opened 2022-09-28 03:44 UTC
After the latest update some games doesn't display correctly in 16:9 aspect ratio in a fullscreen with widescreen option checked. That option must be unchecked and than those games displays properly. Some games displays properly only when this option is checked. So every time you must check it or uncheck it manually. Before the update all the games displayed correctly with widescreen option checked with no need for manual tweaks. 
Flycast flatpak installed on Manjaro KDE Plasma with Graphics APi set to Vulkan
Intel Silver N6000 with Intel UHD  Graphics, 8GB RAM

**Comment by flyinghead** [comment] 2022-09-28 08:14
Please list some games that have this widescreen issue.

**Comment by Branislav84** [comment] 2022-09-28 19:49
Dead or Alive 2, Soulcalibur, Virtua Striker 2 for example. Also Dreamcast
bios doesn't show properly.

**Comment by Branislav84** [comment] 2022-09-28 23:08
Here are the screenshots in attachment from settings, config file and from
Dead or Alive 2. When widescreen option is checked it displays Dead or
Alive 2 with black borders, when widescreen option is unchecked it displays
it without border. It is doing a opposite of what it should be doing. As I
said before I run Flycast flatpak on Manjaro KDE Plasma with Graphics API
set to Vulkan on Intel Silver N6000 with Intel UHD Graphics, 8GB RAM and on
secondary display (TV with resolution 1366x768), primary display is laptop
display with resolution 1920X1080. I set the resolution of Flycast manually
in cfg file (1366x768, fullscreen). Everything was working perfectly until
the last update.

**Comment by Branislav84** [comment] 2022-09-28 23:29
Update - on primary display it is doing a same thing.
Also with game Virtua Fighter 3tb without widescreen option checked it displays a game in 4:3 format, with widescreen option checked it displays it in 16:9 format like it supposed to.  But with Dead or Alive 2, Soulcalibur, Crazy Taxi 2, Sonic Adventure, Ready to Rumble 2 and all other games that I have it is doing the opposite. But before the latest update it was working like it supposed to.

**Comment by Branislav84** [comment] 2022-09-29 02:05
Another update - I found a workaround so everything works without manually tweaking every time I run a game. I unchecked widescreen option, installed widescreen hex patch for Virtua Striker 2 and Virtua Fighter 3tb (replaced codes) with Bless Hex Editor and set horizontal stretching to 134. Now every game works perfectly in 16:9 aspect ratio automatically.

**Comment by flyinghead** [comment] 2022-09-29 08:12
![Screenshot from 2022-09-29 10-10-40](https://user-images.githubusercontent.com/16261910/192977390-af3171a1-436b-4918-84e1-bc0e22f065f8.png)

**Comment by Branislav84** [comment] 2022-09-29 13:26
I sent you screenshots via e-mail (check your mail). Thanks for your screenshot. I can run Soulcalibur in widescreen properly. That is not a problem, problem is that I run it with widescreen option unchecked. Before the update it ran at 16:9 (widescreen mode) with widescreen option checked like it supposed to. With widescreen option unchecked it should run at 4:3 aspect ratio. But no it runs at 16:9 when the option is unchecked and when the option is checked it still runs at 16:9 but with black borders at the top and at the bottom of the screen. That is the issue. But as I said I found I workaround and now all the games works properly automatically.

**Comment by flyinghead** [comment] 2022-09-29 15:18
I haven't received any screenshot by email. Please attach them to this issue as this is much easier to work with.

I understand what you say but I cannot reproduce the issue, as evidenced by the screenshot above (with widescreen enabled). For comparison, here a screenshot with widescreen disabled:
![Screenshot from 2022-09-29 17-15-19](https://user-images.githubusercontent.com/16261910/193071000-4d1ac850-d70a-4787-a9ec-345eab3fdd93.png)

As expected there are black bars on the sides.

Please enable logging and post the resulting flycast.log file. Also your emu.cfg would help too.

Since you have multiple screens, it is possible that there is some confusion with the current screen resolution. A good test would be to retry with only one screen attached.

**Comment by crashGG** [comment] 2022-09-29 18:41
I think the latest version does make some changes in the widescreen settings.
with Dead or Alive 2 (Japan) (Shokai Genteiban), the tests are as follows:

1.no wild screen,all good :
<img width="960" alt="nowild" src="https://user-images.githubusercontent.com/80488411/193113160-9037438b-256f-4470-bea5-e7b9d370e21f.png">

2.wildscreen cheats + wildscreen hack,The screen seems to have become super wide:
<img width="960" alt="superwide" src="https://user-images.githubusercontent.com/80488411/193114047-c701258b-f734-4c1b-9ca7-1642e8bcab4a.png">

3. only wildscreen cheats,3D  scale is ok,2D hud scale are stretched wider:
<img width="960" alt="wildcheat" src="https://user-images.githubusercontent.com/80488411/193114489-e9b4856c-246e-48e2-8d99-be4a00295b45.png">
<img width="960" alt="wildcheat2" src="https://user-images.githubusercontent.com/80488411/193114553-e4448f4a-489b-4dc5-891d-ea9fe6b4ff06.png">

4. only wildscreen hack,2D scale is ok,3D polygons are broken at the edges of the screen:
<img width="960" alt="wildhack" src="https://user-images.githubusercontent.com/80488411/193114830-b1f74e20-c625-44ba-885d-65a89a8eaeb8.png">

<img width="960" alt="wildhack2" src="https://user-images.githubusercontent.com/80488411/193114853-1fefcf6e-24e9-4678-a80e-abab1e6d2cf7.png">


The obvious difference from the previous version is the second one. Because I always have both wild screens open by default. This probably happens after the dev branch was merged into the master branch a few days ago

**Comment by crashGG** [comment] 2022-09-29 19:01
In addition, the phenomenon that the screen becomes super wide when both widescreen options are enabled does not occur in all games, such as with Soulcalibur (USA) the screen ratio is super wide, but with Soulcalibur (Japan) the screen ratio is 16:9.so strange

**Comment by flyinghead** [comment] 2022-09-29 19:27
Thanks @crashGG  for the testing.
Indeed the second test doesn't look right.
Have you tested if this happens with standalone too?

Also, it probably doesn't happen if there's no widescreen cheat for a game.

**Comment by Branislav84** [comment] 2022-09-29 19:58
Ok, I will send you screenshots and log files attached to the issue as soon as I come home. I do not use flycast through RetroArch, I use it as standalone flatpak application on Manjaro KDE Plasma, I am not a fan of RetroArch, had some bad experience with it. Standalone app is much better. Also I only emulate Dreamcast and PSP and use standalone Flycast and standalone PPSSPP.  Maybe it has something to do with widescreen cheats, but I did not installed any of them in Soulcalibur nor Dead or Alive 2. Maybe cheats came by default with the roms that I downloaded from CDRomance. But it worked fine before latest update. And all roms I downloaded are for USA region, except Virtua Striker 2, which is for EU region.

**Comment by crashGG** [comment] 2022-09-29 21:03
> Thanks @crashGG for the testing. Indeed the second test doesn't look right. Have you tested if this happens with standalone too?
> 
> Also, it probably doesn't happen if there's no widescreen cheat for a game.


<img width="960" alt="2022-09-29_235700" src="https://user-images.githubusercontent.com/80488411/193141227-ee67b2f5-ee54-4510-bbf0-f2e982d3d55f.png">
Dead or Alive 2 (Japan) (Shokai Genteiban)

<img width="960" alt="2022-09-29_235926" src="https://user-images.githubusercontent.com/80488411/193141243-e65337f9-c8c2-4c68-abc4-5a1b5f3cd3cb.png">
Soulcalibur (USA)

yes,this happens with standalone too,when both widescreen cheats and hack options are enabled

**Comment by flyinghead** [comment] 2022-09-30 09:53
Ok, I understand now and yes, something has changed in this version: Widescreen Hack and Widescreen Cheats can now be combined. This means that when both options are enabled, and if there is a widescreen cheat for the current game, the resulting aspect ratio will be ~ 21:9.

If you want a normal 16:9 aspect ratio, disable Widescreen Hack or Widescreen Cheat.

**Comment by Branislav84** [comment] 2022-09-30 10:28
I figured that out, now I play all games with widescreen hack disabled and
everything looks good. Thanks for the support.

**Comment by cinnamonmatexfce** [comment] 2022-09-30 10:32
> Ok, I understand now and yes, something has changed in this version: Widescreen Hack and Widescreen Cheats can now be combined. This means that when both options are enabled, and if there is a widescreen cheat for the current game, the resulting aspect ratio will be ~ 21:9.
> 
> If you want a normal 16:9 aspect ratio, disable Widescreen Hack or Widescreen Cheat.
> 

Hey @flyinghead !
What would be the *proper* way (if there's any...) to set the Widescreen mode ?
Users should prefer `Hack` mode or the `Cheat`mode?

Thank you

**Comment by flyinghead** [comment] 2022-09-30 10:50
Widescreen cheat, if available, will usually give you better results, and less 3D clipping. On the minus side the HUD and on screen text is often stretched in this mode.

**Comment by crashGG** [comment] 2022-09-30 13:27
> Ok, I understand now and yes, something has changed in this version: Widescreen Hack and Widescreen Cheats can now be combined. This means that when both options are enabled, and if there is a widescreen cheat for the current game, the resulting aspect ratio will be ~ 21:9.
> 
> If you want a normal 16:9 aspect ratio, disable Widescreen Hack or Widescreen Cheat.

Is it possible not to have the two effects combined, like the previous version did? After all, a super wide effect is not what users want to see.

**Comment by normchomsky** [comment] 2022-10-21 16:17
https://forums.launchbox-app.com/files/file/3646-sega-dreamcast-norms-true-169-project-no-stretching-play-dreamcast-games-in-widescreen-with-no-pop-in-config-files-for-flycast-core-in-retroarch/

I did a whole thing on widescreen for DC. Not all cheat codes yield the same results, the same for the Widescreen hack. I tested pretty much the entire library and noted my findings in the above link. Widescreen hacks/cheats do invariably have some sort of menu stretching and miss alignment, it's more about the in game experience. You gotta forgive it a little as you're forcing widescreen on games that were not designed with it in mind.

**Closed** 2022-12-23 21:55 UTC
