### ISSUE TITLE
[Naomi] The Maze of The Kings (GDS-0022) | Sound cutting out + crosshair overshooting

### ISSUE THREAD

**Issue by Gomam0n-afk** [flyinghead/flycast#858] opened 2023-01-10 09:35 UTC
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: Windows 10 22h2

Github hash: 

Hardware: i7-7700 GTX 1060 6GB

**_Description of the Issue_**

Add a short, concise description of the issue here

The crosshair in this game overshoots in all 4 axis the more you are away from the center.
Shooting sounds among others cut out or don't play outright depending on what's happening. the issue acts a lot like a lack of enough sound channels.

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

**_Screenshots_**

My sound settings : 
![flycast_goafAkz4de](https://user-images.githubusercontent.com/59240947/211514299-fc5ced4e-0481-4248-9627-641986ad12af.png)

Crosshair issue showcased : 
![flycast_flKP6wrL5C](https://user-images.githubusercontent.com/59240947/211514423-5593de9e-749b-45c9-8a8f-0435b8283de5.jpg)
The crosshair aligns perfectly to the center.
![flycast_HWZryay7Zk](https://user-images.githubusercontent.com/59240947/211514414-d33c6da6-b360-4457-bdbc-209be657dbf8.jpg)
But the more you are away from the center the more out of place it becomes.

**Comment by flyinghead** [comment] 2023-01-10 10:13
The crosshair issue can be solved by doing a gun calibration in the game test menu.
![image](https://user-images.githubusercontent.com/16261910/211523321-4fb1be37-c195-4c6e-8e1a-2cca2d226a3c.png)

**Comment by flyinghead** [comment] 2023-01-10 10:13
The sound issue is a duplicate of #483.

**Closed by flyinghead** 2023-01-10 10:13 UTC
Labels: bug
