### ISSUE TITLE
Again,  Sega GT Homologation Special, bug with rear lights

### ISSUE THREAD

**Issue by melek8014** [flyinghead/flycast#1695] opened 2024-10-13 22:08 UTC
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
MS Windows 7 64-bit SP1, AMD Athlon X4 880K Quad Core Processor, 12GB RAM, GeForce 8800 GT
Flycast version: 
latest master version
Hardware: 

**_Description of the Issue_**
During night driving, dark spots appear on the rear lights of the vehicle, as seen in the photo ( I circled it in green) on the left headlight of the car, This is visible only on some cars that have large rear headlights, the HONDA Z car in the photo
Add a short, concise description of the issue here  [ I came back to this graphical problem again, compared it with the Redream emulator and there is no problem with these rear lights, and I also play on per strip, I am also posting a photo from the Redream emulator, on the HLE (per-strip) setting there is no problem with lights, but on Flycast (per-strip) there is this problem... ] 

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

```

Please paste the contents of the log / logs here
You may leave this field blank if you have none.

```

![361581720-cd835758-1606-41d7-aab0-5dcdb69df2ef](https://github.com/user-attachments/assets/0c50fe47-70ef-4351-bf63-1263e7143b16)

**_Screenshots_**
![Bez tytułu](https://github.com/user-attachments/assets/3c6d7f53-855a-4013-9d84-38c2d03f39e6)

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment] 2024-10-14 07:08
duplicate of #1617.
related to #100.

**Closed by flyinghead** 2024-10-14 07:08 UTC
Labels: bug
