### ISSUE TITLE
Please add multiple button mapping.

### ISSUE THREAD

**Issue by Kiminari-Suzuki** [flyinghead/flycast#1396] opened 2024-02-12 12:51 UTC
Please add multiple button mapping.
For example. 6 Button fighting game.
Button / Mapping
X / X L2 (Small punch)
Y / Y L2 (Middle punch)
L / L1 L2 (Big punch)
A / A R2 (Small kick)
B / B R2 (Middle kick)
R / R1 R2 (Big kick)
Then, L2 works for 3 punch buttons, R2 works 3 kick buttons at once.

**Comment by blueminder** [comment] 2024-02-12 13:06
FWIW, it's already available in [Flycast Dojo](https://github.com/blueminder/flycast-dojo/). These combinations are listed under the "Macros" section of the controller mapping screen. 

![image](https://github.com/flyinghead/flycast/assets/504581/25c89824-d065-4376-8602-aa384ed245f5)
![image](https://github.com/flyinghead/flycast/assets/504581/939a2fba-9170-495e-8324-0191527262ba)

**Comment by Kiminari-Suzuki** [comment] 2024-02-12 13:16
Oh, thank you. I will try it.

**Comment by flyinghead** [comment] 2024-02-13 18:12
duplicate of #274

**Closed by flyinghead** 2024-02-13 18:12 UTC
Labels: enhancement
