### ISSUE TITLE
PS4 controller not work in Flycast-2.1, but Flycast-2.0 is work (macOS M2 Pro)

### ISSUE THREAD

**Issue by SolidZORO** [flyinghead/flycast#1228] opened 2023-10-08 12:01 UTC
Hardware: 

macOS M2 Pro Sonoma 14.0 / Memory 32G / 14 inch

Flycast-2.1 as V2.1 (a21b79cf) ❌ not work

Flycast-2.0 as V2.0 (aa97a6d6) ✅ work

Both versions are initial configurations

**Comment by flyinghead** [comment] 2023-10-08 13:16
Try the latest master build here (first one at the top of the list):
https://flyinghead.github.io/flycast-builds/

**Comment by SolidZORO** [comment] 2023-10-09 01:27
@flyinghead I'm download v2.1 (4e079b5d0)  everything is perfect! thanks.

https://flycast-builds.s3.amazonaws.com/osx/heads/master-4e079b5d0bf9e4335d4153be42d531f99e80dea8/flycast.app.zip

**Comment by SolidZORO** [comment] 2023-10-09 01:35
@flyinghead  I'm sorry, I haven't been thoroughly tested. Just entering the game, I found that the PS4 controller can be used, but there is a delay, and many times I need to press the button twice for it to take effect. 

For example, if I want to press the up button, it doesn't respond the first time and requires another press.

**Comment by vkedwardli** [comment] 2023-10-09 03:21
Duplicate of https://github.com/flyinghead/flycast/issues/1044

are you using Bluetooth or wired connection?

**Comment by SolidZORO** [comment] 2023-10-09 03:51
@vkedwardli Both BT and wired have this problem.

**Comment by vkedwardli** [comment] 2023-10-09 03:54
Please use the [240p test suite](https://artemiourbina.itch.io/240p-test-suite) to verify the input delay/double input problem

**Comment by SolidZORO** [comment] 2023-10-09 04:38
@vkedwardli  I downloaded 240p-DC-PVR-2.03/240pSuite.cdi  and run.

Flycast-2.1 as v2.1-DEV (4e079b5) ❌ not work
That's as far as it goes, and then it goes **Black screen, freeze**, can't verify the input.
<img width="1130" alt="image" src="https://github.com/flyinghead/flycast/assets/661587/a84406ca-2ddf-437c-acf5-b2c9eb2a4d6d">


Flycast-2.0 as V2.0 (aa97a6d6d) ✅ work
**Can work properly, controller test**
<img width="1130" alt="image" src="https://github.com/flyinghead/flycast/assets/661587/e7b624b6-bce7-4fe8-aa27-8ed10c605f9a">

**Comment by flyinghead** [comment] 2024-10-18 14:36
Assuming this is fixed. Reopen if not.

**Closed by flyinghead** 2024-10-18 14:36 UTC
Labels: bug, input
