### ISSUE TITLE
Samurai Spirits Tenkaichi Kenkakuden graphical glitches

### ISSUE THREAD

**Issue by XieTieqiang** [flyinghead/flycast#722] opened 2022-08-26 07:46 UTC
Samurai Spirits Tenkaichi Kenkakuden，when character select, the background blocks the portrait of the person.

Renderer: vulkan
Alpha Sorting: Per-Pixe
![samsptk](https://user-images.githubusercontent.com/95056895/186850992-a08d4218-20fb-4f33-bdf6-ea90d1fa2752.jpg)
l

**Comment by flyinghead** [comment] 2022-08-26 08:07
Duplicate of #136.

> This game uses very large depth (Z) values. To compensate for this, depth values are reduced, which may affect other views (such as the BIOS boot).
> Also this fixes most issues during a fight, but many depth issues remain on menus, interstitial screens, etc. Unfortunately, fixing one breaks the other and vice-versa...

**Closed by flyinghead** 2022-08-26 08:07 UTC
Labels: bug

**Comment by flyinghead** [comment] 2024-02-07 21:12
The latest `dev` build has a fix for this game. Feedback welcome.

**Comment by Immersion95** [comment] 2024-02-07 22:16
> The latest `dev` build has a fix for this game. Feedback welcome.

Works perfectly :)

**Comment by Immersion95** [comment] 2024-02-08 11:01
@flyinghead : Can this fix also help with Capcom vs. SNK Pro Ending protrait not being displayed ?

https://github.com/libretro/flycast/issues/890

**Comment by flyinghead** [comment] 2024-02-08 12:50
Just checked and, no, it doesn't help
