### ISSUE TITLE
[Nintendo Switch] Skies of Arkadia freezes

### ISSUE THREAD

**Issue by Photon324** [flyinghead/flycast#1312] opened 2023-11-20 16:11 UTC
Skyes of Arkadia freezes almost at the very beginning when meeting Alfonso. I tried all versions of the emulator (1.2, 2.1, 2.2) and the game in the European and US regions. There is no such problem with the Android and PC versions.
I apologize if I didn’t describe the problem very clearly, I’ll translate it through Google translator.

**Comment by flyinghead** [comment] 2023-11-24 09:58
Thanks for trying all versions. Since it doesn't happen on other platforms I assume this is a Switch-specific bug. Unfortunately I don't have switch to try to reproduce it. I'll see if I can get some help from a dev that owns one.

**Comment by flyinghead** [comment] 2024-01-17 18:55
Should be fixed in the latest `dev` build

**Comment by Photon324** [comment] 2024-01-19 14:29
Thank you very much, it works great now

**Closed** 2024-01-27 21:42 UTC
Labels: bug
