### ISSUE TITLE
Cannot launch from Android ES-DE - Side Effect from Flycast 2.2

### ISSUE THREAD

**Issue by nevmind** [flyinghead/flycast#1584] opened 2024-07-20 12:01 UTC
Platform / OS / Hardware: Android

Precondition.
- install Flycast 2.3 apk
- install ES-DE_3.0.3-26

Test Procedure.
1. Run ES-DE in Android.
2. select button on any naomi game to set altemulator to "Flycast (Standalone)" which means Flycast standalone app.
3. See if game is launched correctly or not.

Actual Result : 
Just display Flycast gamelist screen. and doens't start game.

Additional Info. : 
Flycast 2.0 : no problem
Flycast 2.1 : no problem
Flycast 2.2 : has problem
Flycast 2.3 : has problem

Flycast 2.3.2-164-g33d1afdb in Android Playstore (Git Hash : 33d1afdb) : 
has problem and  
1 more problem  ->  cannot be recognized as standalone emulator by following es_find_rules.xml of ES-DE

    <emulator name="FLYCAST">
        
        <rule type="androidpackage">
            <entry>com.flycast.emulator/com.reicast.emulator.MainActivity</entry>
        </rule>
    </emulator>

So, I have tried modifed following es_find_rules.xml  ->  can be recognized as standalone emulator but doesn't launch game.

    <emulator name="FLYCAST">
        
        <rule type="androidpackage">
            <entry>com.flycast.emulator/com.flycast.emulator.MainActivity</entry>
        </rule>
    </emulator>

Are u changing package name of MainActivity? Need to specify clearly to ES-DE team. So they can change es_find_rules.xml correctly.

**Comment by nevmind** [comment] 2024-07-21 07:43
updated more information about this bug

**Comment by flyinghead** [comment] 2024-07-21 08:47
This regression is due to this change: 87fdd203b57fae24ae25e30613726f6a8a6fb2a0, which was included in 2.3. I will push a fix soon.

I also changed the name of the main activity from `com.reicast.emulator.MainActivity`to `com.flycast.emulator.MainActivity` but this is a recent change and doesn't impact v2.3.

**Comment by SilverGreen93** [comment] 2024-07-31 09:47
So is this something that needs fixing on flycast side? Or should we talk to ES-DE as well to update the activity name?

**Comment by flyinghead** [comment] 2024-07-31 12:36
A fix is also needed on the Flycast side, which I haven't committed yet.

**Comment by nevmind** [comment] 2024-08-10 22:10
When is next fixed version supposed to be released?

**Comment by nevmind** [comment] 2024-08-21 11:49
> Fixed on Google Play

Very Thanks. It works now!!!

**Closed** 2024-10-13 17:35 UTC
Labels: bug, regression, UX
