### ISSUE TITLE
Virtua Tennis/Power Smash (NAOMI) Some pars of the intro are gray

### ISSUE THREAD

**Issue by TheCoolPup** [flyinghead/flycast#1426] opened 2024-02-26 22:54 UTC
Platform / OS / Hardware: Windows 11, AMD Ryzen 5600H @3.3GHz, Nvidia RTX 3050ti Laptop GPU

Github hash: b5eecb7

Some parts of the intro, mostly where it shows the tennis players in a match, are grayed out, happens on per pixel, triangle, and strip.

![Flycast 2_26_2024 5_54_01 PM](https://github.com/flyinghead/flycast/assets/91135037/aefa7017-2ca9-48f6-a5f0-249c4d13cdc0)

**Comment by flyinghead** [comment] 2024-02-27 08:41
Enable `Video > Render to Texture > Copy to VRAM`. It is not enabled by default for this game because it makes replays very slow on low end platforms.

![image](https://github.com/flyinghead/flycast/assets/16261910/8a224208-c836-4807-93cf-d3a190da27ad)

**Comment by flyinghead** [comment] 2024-02-27 08:43
Duplicate of #729

**Closed** 2024-04-04 19:46 UTC
Labels: graphics
