### ISSUE TITLE
About Android shell running commands

### ISSUE THREAD

**Issue by clondy999** [flyinghead/flycast#226] opened 2021-04-20 07:54 UTC
Hello~
I would like to ask, in the Android environment, can I use adb shell to quickly start flycast and load the game? What is the command format?

**Comment by flyinghead** [comment] 2021-04-20 08:13
To start Flycast:
```
adb shell am start -n com.flycast.emulator/com.reicast.emulator.NativeGLActivity
```
To start Flycast with a given content:
```
adb shell am start -n com.flycast.emulator/com.reicast.emulator.NativeGLActivity -a android.intent.action.VIEW -d file:///storage/emulated/0/Download/some_game.chd
```

**Comment by clondy999** [comment] 2021-04-20 08:15
The command I entered is:
am start --user 0 -n com.flycast.emulator/com.reicast.emulator.MainActivity -a android.intent.action.VIEW -d "/storage/external_storage/sda1/sp/dolphin.zip"

But it will only enter Flycast, but the game content is not automatically loaded

**Comment by clondy999** [comment] 2021-04-20 08:19
I tried your command, the situation is the same, it will only enter the program, but the content is not loaded

**Comment by flyinghead** [comment] 2021-04-20 08:36
The path to your content is probably wrong, or it could be a permission problem. Also it will not start a game is the app/activity is already running.

Any message from adb when running the command?

Here is what I get:
App already running and top-most:
```
Starting: Intent { act=android.intent.action.VIEW dat=/storage/emulated/0/Download/whatever.cdi cmp=com.flycast.emulator/com.reicast.emulator.NativeGLActivity }
Warning: Activity not started, intent has been delivered to currently running top-most instance.
```
App already started in the background:
```
Starting: Intent { act=android.intent.action.VIEW dat=/storage/emulated/0/Download/whatever.cdi cmp=com.flycast.emulator/com.reicast.emulator.NativeGLActivity }
Warning: Activity not started, its current task has been brought to the front
```

**Comment by clondy999** [comment] 2021-04-20 08:38
The terminal returns:
EW -d /storage/external_storage/sda1/sp/dolphin.zip <
Starting: Intent {act=android.intent.action.VIEW dat=/storage/external_storage/sda1/sp/dolphin.zip cmp=com.flycast.emulator/com.reicast.emulator.NativeGLActivity}

Did not see an error

**Comment by clondy999** [comment] 2021-04-20 08:40
I'm sure I will run the command after closing the program. I have also tried to enter the command when the program exists, it will always be black

**Comment by clondy999** [comment] 2021-04-20 08:59
I think I may have downloaded a modified APK. Where can I get the official APK, I try to reinstall it

**Comment by flyinghead** [comment] 2021-04-20 09:07
https://flyinghead.github.io/flycast-builds/

**Comment by clondy999** [comment] 2021-04-20 09:12
I downloaded the official version, but the situation has not changed. After entering the command, I only enter the program, but the content is not loaded
adb shell return content:

```
EW -d /storage/external_storage/sda1/sp/111.chd                               <
Starting: Intent { act=android.intent.action.VIEW dat=/storage/external_storage/sda1/sp/111.chd cmp=com.flycast.emulator/com.reicast.emulator.NativeGLActivity }
```

**Comment by clondy999** [comment] 2021-04-20 09:13
The command I entered:

`/system/bin/am start -n com.flycast.emulator/com.reicast.emulator.NativeGLActivity -a android.intent.action.VIEW -d /storage/external_storage/sda1/sp/111.chd`

**Comment by clondy999** [comment] 2021-04-20 09:23
Is there any way to test and solve the problem?

**Comment by flyinghead** [comment] 2021-04-20 14:30
The strange thing is: if I pass an invalid content (CHD or CDI), Flycast will start the BIOS. If I pass an invalid ZIP file, Flycast displays the message `Unknown game`.

In all cases Flycast attempts to open the content.

**Comment by clondy999** [comment] 2021-04-20 14:34
Thank you for your continued attention to this issue.
I have been testing this work, I make sure that the game ROM can be loaded, because I try to manually load the ROM on the main interface is normal, but the command runs until the main interface does not load the game

**Comment by clondy999** [comment] 2021-04-20 14:37
I just tried to load a non-existent game ROM, adb still returned the same information, and did not prompt other

```
EW -d "/storage/external_storage/sda1/362.cdi"                                <
Starting: Intent { act=android.intent.action.VIEW dat=/storage/external_storage/sda1/362.cdi cmp=com.flycast.emulator/com.reicast.emulator.NativeGLActivity }
root@m201:/ #
```

**Comment by clondy999** [comment] 2021-04-20 14:39
In addition, I also use reicast for testing.
There is no problem with reicast and it can be loaded into ROM, but I don’t know why it will prompt a certain CPP file to report an error after entering the game.
But I still like to use flycast, it does a better job

**Comment by clondy999** [comment] 2021-04-20 14:41
Can you tell me the version of flycast you use? In addition, my Android version is 4.4

**Comment by flyinghead** [comment] 2021-04-20 14:55
The problem is due to Android 4.4. I'll push a fix for it.

**Comment by clondy999** [comment] 2021-04-20 14:58
Thank you so much for your contribution!

**Comment by clondy999** [comment] 2021-04-20 15:46
I will always follow this post, if you fix and package the APK file, please let me know, thank you very much

**Comment by flyinghead** [comment] 2021-04-20 15:50
It's fixed in version https://github.com/flyinghead/flycast/commit/a9e22c2e20b5a408e6a4a69f4dcce743e869dff3
You can download it on the builds page.

**Comment by flyinghead** [comment] 2021-04-30 20:09
Assuming this is fixed. Reopen if not.

**Closed by flyinghead** 2021-04-30 20:09 UTC
Labels: bug
