### ISSUE TITLE
Blue Stinger (Japan) rendering bug

### ISSUE THREAD

**Issue by crashGG** [flyinghead/flycast#720] opened 2022-08-24 17:30 UTC
Platform / OS / Hardware: win10 1809

flycast: newest master and dev

Hardware: intel i3 + hd 5300 + dx11

Issue:
Blue Stinger (Japan) ,Weird rendering error at the beginning of the game
<img width="480" alt="jp" src="https://user-images.githubusercontent.com/80488411/186484812-d087c333-9e74-495f-8dc0-f3a0bc66c377.png">

But the US version is ok
<img width="480" alt="usa" src="https://user-images.githubusercontent.com/80488411/186484929-7f8ccb0d-b4bf-4dff-b89c-813e37b9400f.png">

**Comment by flyinghead** [comment] 2022-08-24 18:26
Duplicate of #622. Increase the max number of layers to fix the glitch.

**Closed by flyinghead** 2022-08-24 18:26 UTC
Labels: bug

**Comment by crashGG** [comment] 2022-08-24 18:56
> Duplicate of #622. Increase the max number of layers to fix the glitch.

Don't rush to close this issue, the option I used is per triangle, different from #622 , and there is no such option“maximum layers”. and  Under the same configuration,the US version is ok, the Japanese version is not ok, isn't it a bit strange?

**Comment by flyinghead** [comment] 2022-08-24 19:21
Then, it's probably a glitch due to per triangle, which happens for the JP version and not the US one. This scene has more than 32 transparent layers, and per triangle is only an approximation. Only per-pixel is accurate.

**Comment by crashGG** [comment] 2022-08-25 07:33
> per-pixel

By the way, when I use the redream emulator(per-strip) ,the  Japanese version and the US version both display fine. The reason why per-pixel is not used is that most intel graphics cards cannot  use it  for performance reasons.
