### ISSUE TITLE
Text message too fast in death crimson 2

### ISSUE THREAD

**Issue by PalFanTw** [flyinghead/flycast#646] opened 2022-05-28 09:09 UTC
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: win10

Github hash: 

Hardware: I9 9900k rtx 2060 16g ram

**_Description of the Issue_**

Text message display too fast in death crimson 2 (japan ver) when use light gun.
It is impossible to read the text.
It is no problem when use sega controller.

**_Debugging Steps Tested_**

1.set device A to light gun
2.play story mode

**Comment by flyinghead** [comment] 2022-06-30 12:06
I can reproduce the problem. It seems the wait for button A/trigger press in dialogs (when a triangle is shown) doesn't work when using a light gun. However the trigger works for multiple answer choices and in battles.

I double-checked the light gun emulation code and tried a number of things to no avail. Given the overall quality of this game, I wouldn't exclude a game bug.

**Comment by PalFanTw** [comment] 2022-09-02 03:23
> I can reproduce the problem. It seems the wait for button A/trigger press in dialogs (when a triangle is shown) doesn't work when using a light gun. However the trigger works for multiple answer choices and in battles.
> 
> I double-checked the light gun emulation code and tried a number of things to no avail. Given the overall quality of this game, I wouldn't exclude a game bug.

I try to play this game with real dreamcast and light gun and it works well. I think it is not a game bug.

https://user-images.githubusercontent.com/97172513/188051987-e46b852e-aef2-4f14-bbf9-c6974fbf0512.mp4

**Comment by kihato** [comment] 2023-12-16 07:12
Github hash: 5fde889

I'm not sure if this helps, but I found that setting "Densha Controller" to port B causes the exact same bug as the light gun.
After examining the code, it seems that a fast forward bug occurs in densha_controller when both the 7th and 6th bits of the return value of getAnalogAxis are set.
Similarly, in lightgun, it seems to occur if the return values of index==0 and index==1 of maple_sega_controller's getAnalogAxis are both 0.

However, if I simply set it to a value other than 0, the mouse buttons would no longer work, so I couldn't figure it out any further.

**Comment by flyinghead** [comment] 2023-12-16 15:55
Great find once again @kihato !

The maple documentation states that the light gun must return 255 for the trigger axes value. However it looks like this isn't what the actual light gun is returning.
When using a gamepad, the player can fast forward through the dialogs by pressing the left trigger. And this is what was happening with the light gun.
Returning 0 for the triggers fixes the problem.

Should be fixed in the next master build.

**Closed** 2024-01-03 18:52 UTC
Labels: bug, input
