### ISSUE TITLE
Skies of Arcadia - Icons incorrectly displaying in battle transition

### ISSUE THREAD

**Issue by TreeBranches** [flyinghead/flycast#1127] opened 2023-06-26 22:22 UTC
Platform / OS / Hardware: 

Ryzen 5700G/8GB RAM/Batocera Linux (Retroarch Core) 

**_Description of the Issue_**

This May be specific to Skies of Arcadia. Happens on both PAL and NTSC. 

During all parts of the game, when entering into battle, the pause menu that's available during the airship flight, and certain screen effects when a battle is won, the bottom of the screen displays all of the menu icons in the freeze frame when it shouldn't. 

ReDream replaces this with a black bar though I don't believe that to be correct either going by YouTube videos. It seems like what happens on original hardware is the frame "gets wider than it should" for that transition, but maintains the correct vertical height. 

[Video of how it's supposed to look on original hardware](https://youtu.be/bdVTY5UFCxE?t=270) 

**_Debugging Steps Tested_**

As advised on the Flycast Discord I tried to have both "Full Frame buffer emulation" and "Render To Texture Buffer" enabled. No combination of these settings resolved this particular issue. 

**_Logs Gathered_**

No logs as it's not relevant (no crashes), but below I've linked my VMU containing the Skies of Arcadia PAL save and the Retroarch game config I used. 

After loading the save, you'll be present on an airship. Simply press start to pause the game and replicate the screenshot shown above, or move around for a few seconds to enter a battle and display the transition. 

[VMU Save](https://drive.google.com/file/d/1Qgf5VD9WNS0RyRD51YPZmaeMtH3EUhVu/view?usp=drivesdk) 

[Skies of Arcadia PAL game specific configuration for Retroarch](https://drive.google.com/file/d/1QbOvgR75ay-Ib7wS41drwg2YPLHwS3DW/view?usp=drivesdk)

**_Screenshots_**

![Screenshot of Pause Menu](https://github.com/flyinghead/flycast/assets/8653544/619c09f4-5fbe-45ff-8f63-ce77b970f4c7)

[Video of transition animation of Flycast](https://drive.google.com/file/d/1QgkhOVF9hVLHH6MBy-h5DvZlzF3JQgJ8/view?usp=drivesdk)

[Video of transition animation on ReDream](https://drive.google.com/file/d/1QlfuOLH24ZJpM1oCJ454rtWPpUTxq8gP/view?usp=drivesdk)

**Comment by flyinghead** [comment] 2023-06-28 08:25
Which version of the flycast core are you using?
Which graphics driver?

I can't reproduce the issue with the current core version:
![image](https://github.com/flyinghead/flycast/assets/16261910/91de188f-5d17-4f34-b9d8-ef441d307008)

**Comment by TreeBranches** [comment] 2023-06-28 19:54
Flycast on Retroarch v1.15.0 using Batocera Linux v37. I don't see a version number in the information screen as it just says "Core Version: Git", but Batocera's change log says "flycast emulators to Apr 4, 2023 build" 

Using the glcore driver.

**Comment by flyinghead** [comment] 2023-06-28 20:32
I have no idea what it means.

Please test the latest Flycast core version. Testing latest standalone would be helpful too.

**Comment by vkedwardli** [comment] 2023-06-29 09:33
[Version: Commits on Apr 4, 2023](https://github.com/batocera-linux/batocera.linux/commit/f704ec96c213fcacecada0cdaab92b36c7052064) should mean `187674ddac84038922bb29a0f89e99ecf3135e52`

But there are many changes already: 
https://github.com/flyinghead/flycast/compare/187674ddac84038922bb29a0f89e99ecf3135e52..master

**Comment by flyinghead** [comment] 2023-06-29 11:13
Thank you for this. But yes, it might have been fixed already so testing the latest version would help.

**Comment by TreeBranches** [comment] 2023-07-09 21:34
Thanks. I'll confirm this when Batocera updates next, using a newer Flycast build.

**Comment by flyinghead** [comment] 2023-10-14 16:23
Assuming this is fixed. Reopen if not

**Comment by kihato** [comment] 2023-10-14 23:49
This seems to be a PAL-specific issue.
This does not happen, at least with standalone NTSC (US version, JP version).

Battle scene transition and pause scene (both PAL versions)
(It's hard to understand, but it will be displayed for a moment.)

https://github.com/flyinghead/flycast/assets/14366233/ab967cc5-88ca-4f97-9b35-c2f924be44ac

https://github.com/flyinghead/flycast/assets/14366233/9190d660-93ac-4f3f-8189-41e0bc735045

**Comment by flyinghead** [comment] 2023-10-16 13:17
Should be fixed in the latest master build

**Closed** 2023-10-22 18:42 UTC
Labels: bug, graphics
