### ISSUE TITLE
Request: Hotkeys for save state

### ISSUE THREAD

**Issue by Leafdomain** [flyinghead/flycast#913] opened 2023-02-09 13:43 UTC
**Is your feature request related to a problem? Please describe.**
Most prominent emulators have the feature to assign hotkeys to the save state load state functionality. For example, Dolphin, PCSX2, Duckstation, and many more. It's an incredibly useful feature and helps in gameplay a lot. Flycast currently allows this only via the pause menu, which disturbs the flow of gameplay very much so. It is currently very cumbersome like this. Save state is meant to be used in a way that supports gameplay, so it would be great if hotkeys could be assigned.

**Describe the solution you'd like**
There already are assignable hotkeys to other features in the control assignment menu. It just needs save state hotkeys added to that part. Both the hotkey assignment and save state functionalities are already features of the emulator. So it just needs to be implemented into the control assignment menu.
I'm sure everyone would appreciate it so much if it gets done.
Thank you so much in advance, and for making such an amazing emulator.

**Comment by flyinghead** [comment] 2023-02-09 13:47
duplicate of #615

**Closed by flyinghead** 2023-02-09 13:47 UTC
Labels: enhancement
