### ISSUE TITLE
Guilty Gear X (Dreamcast) - Music doesn't play in battle unless DC BIOS is present

### ISSUE THREAD

**Issue by smbhax** [flyinghead/flycast#1124] opened 2023-06-24 06:41 UTC
Platform / OS / Hardware: Windows 11

Github hash: https://github.com/flyinghead/flycast/commit/0070f9a

Hardware: 
Intel Core i7-10750H CPU @ 2.69GHz (12 CPUs)
16 GB RAM
NVIDIA GeForce GTX 1660 Ti
S271HL NVIDIA High Definition Audio

**_Description of the Issue_**

Guilty Gear X (Dreamcast GDI)'s 34 music tracks will play from the game's Sound Test screen, but not during fights--unless the user also has the DC BIOS file in Flycast's "data" folder.

As a match begins, without the BIOS, a long series of double messages in the follow format appears in the log:

> 01:43:773 imgread/common.h:251 W[GDROM]: Failed or truncated GD-Rom read
> 01:43:773 imgread/common.cpp:299 W[GDROM]: Sector Read miss FAD: 16947949

I'm not sure if this is a bug or a documentation issue--the Wiki says "A Dreamcast BIOS file is optional," which implies that not having it wouldn't be limiting game functions. https://github.com/TheArcadeStriker/flycast-wiki/wiki/Getting-started-with-Flycast

**_Debugging Steps Tested_**

1) Download a new copy of Flycast
2) Extract it to a new directory
3) Run it and load Guilty Gear X (Dreamcast GDI)
4) Press Start until you get to an Arcade mode match

You will hear music during some menu and load screens, but none during the match itself--until you install a copy of the DC BIOS.

**_Logs Gathered_**:

[flycast.log](https://github.com/flyinghead/flycast/files/11857248/flycast.log)

**_Screenshots_**: None

Video:

https://youtu.be/WbBECIQQ6Mw

**Comment by kihato** [comment] 2023-07-05 01:35
1cadd4e: reproducible (#534)
ab791d1: can't reproduce

I haven't found any other games that affect it so far.

**Comment by smbhax** [comment] 2023-07-05 02:11
Still reproduces for me in latest Windows build (https://github.com/flyinghead/flycast/commit/a870fb7 6/30/23).

**Comment by flyinghead** [comment] 2023-07-05 08:25
Thanks a lot for your help @kihato!
This should be fixed in the next master build.

**Closed** 2023-07-11 08:00 UTC
Labels: bug, audio
