### ISSUE TITLE
Melty Blood: Act Cadenza (ver. B2) Vs. Satsuki black screen

### ISSUE THREAD

**Issue by fgenjoyer** [flyinghead/flycast#1255] opened 2023-10-21 09:16 UTC
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: MIUI, Android 12

Github hash: 35b7be3

Hardware: Redmi 12C

**_Description of the Issue_**
Playing as Kouma, i encountered Satsuki then it goes black screen. I tried using the standalone but still didn't work.

**_Screenshots_**
![Screenshot_2023-10-21-17-15-06-957_com retroarch](https://github.com/flyinghead/flycast/assets/148618204/919769d4-a60f-4957-abdd-a30e066fc653)

**Comment by flyinghead** [comment] 2023-10-21 11:11
Are you using OpenGL or Vulkan? Does it make a difference?
Are you using any non-default Video settings?

Does the issue happen for all matches, or only certain stages/opponents?

I did a quick test on with a Mali-G51 phone and it seems to work fine:
![image](https://github.com/flyinghead/flycast/assets/16261910/dc43e2ab-d085-4ecd-84b4-7534541cdc5f)

Android 10
Driver version: v1.r18p0-01rel0.2842c961d...

**Comment by fgenjoyer** [comment] 2023-10-21 13:00
Yo, i'm using Vulkan right now (i tried changing to OpenGL but didn't work), it only happens on a specific character on a specific stage which is only Satsuki. The bug also happened on my Windows 10, even if i reset my settings nothing change.

I also tried switching from Per-Triangle to Per-Pixel
![Screenshot_2023-10-21-20-31-15-342_com retroarch](https://github.com/flyinghead/flycast/assets/148618204/51a49765-fa31-4618-bca5-d21f649afe0f)
![Screenshot_2023-10-21-20-31-09-112_com retroarch](https://github.com/flyinghead/flycast/assets/148618204/8da13b97-a06c-4938-bd2d-caf0531e07b8)

**Comment by flyinghead** [comment] 2023-10-21 19:17
It looks like it's an old bug I had forgotten about: https://github.com/libretro/flycast/issues/1013
Not related to any platform or GPU in particular. I can reproduce it with standalone on linux too, but only against Satsuki.

**Comment by fgenjoyer** [comment] 2023-10-22 00:03
Any way to fix it? Sometimes i'll get far in the game and then i'll encounter her, so i had to restart again.

**Comment by kihato** [comment] 2023-12-06 02:35
Github hash: 5fde889

I checked back to the commit on Oct 11, 2018 (ff01e35), and it seems that the blackout bug has already existed since then.
Also, the blackout bug occurred outside of the Satsuki battle.

I found that I could avoid the blackout by temporarily changing to an interpreter or lowering the SH4 Clock value.
However, the SH4 Clock value seems to vary depending on the character, and Kouma needs to be adjusted to around 130 and Vermilion to around 147.

If Satsuki appears in stage 1
**Vermilion:** [meltyb.zip](https://github.com/flyinghead/flycast/files/13575139/meltyb.zip)
**Kouma:** [meltyb_1.zip](https://github.com/flyinghead/flycast/files/13575141/meltyb_1.zip)

Other than the match against Satsuki
**Kouma:** [meltyb_4.zip](https://github.com/flyinghead/flycast/files/13575157/meltyb_4.zip)

On a different note, an extra texture is displayed in the upper left corner at the beginning of the ED.
[meltyb_7.zip](https://github.com/flyinghead/flycast/files/13575183/meltyb_7.zip)

![Melty](https://github.com/flyinghead/flycast/assets/14366233/9401bccf-26d1-4165-bf65-f1c14564cea5)

**Comment by flyinghead** [comment] 2023-12-07 16:02
The game is freezing when loading some textures because a vram allocation fails at some point. This allocation failure is caused by other textures not being freed fast enough, or in this case because new textures are being loaded to quickly.
Previous textures (presumably from the beginning of the animation) are only freed after a given number of frames/vblanks. As @kihato found out, slowing down the cpu fixes the issue since the cpu loads new textures slower, while vblank still happens at the same pace. (By the way, the interpreter is *very* underclocked  at around 25 MHz.)

I was able to fix the issue by adding a delay/bandwidth to the Naomi cart DMA instead of it being instantaneous/infinite bandwidth. I had to set it to 20 MB/s. This will affect all Naomi and Atomiswave games so some testing will be needed.

Check latest `dev` build

**Comment by flyinghead** [comment] 2023-12-07 16:15
Looks like #377 is also fixed by this change so this is encouraging.

**Comment by Ambatublow69** [comment] 2023-12-08 04:53
So uhh my dumbass forgot my email on my acc and now i couldn't open it but yeah, it's now fixed. Thanks! 
![Screenshot_2023-12-08-12-40-03-743_com flycast emulator](https://github.com/flyinghead/flycast/assets/134768069/72cef62c-fc93-47cd-8de8-65e2f5b37308)

**Closed** 2023-12-16 18:43 UTC
Labels: bug
