### ISSUE TITLE
Confidential Mission - Missing sounds

### ISSUE THREAD

**Issue by dukeblooders** [flyinghead/flycast#472] opened 2021-12-30 20:02 UTC
Some sounds, especially the reload one, are skipped/not played on Naomi and Dreamcast.

It starts at the beginning of the game, just after the first corner.

Configuration : Windows 10, flycast standalone (latest nightly)

**Comment by flyinghead** [comment] 2022-04-30 14:14
Some reload sounds are missing at some times. However it seems to be intermittent. Same behavior in dreamcast and Naomi versions.

**Comment by flyinghead** [comment] 2023-12-31 11:24
Should be fixed in the  latest dev build.

**Comment by dukeblooders** [comment] 2024-01-03 17:55
Tested with the latest dev build and it works like a charm! 

Thanks

**Comment by kihato** [comment] 2024-08-30 14:53
Unfortunately, there was a regression caused by b468c9b.
However, it seems to only affect #472 and #1180.

**Comment by kihato** [comment] 2024-09-06 14:42
It seems that `enabled=false` in `disable()` affects #472 and #1180.
So I tried setting `ch->CA=0` in `EG_Release`.
I tested it in this state and there were no more reboots or audio issues.

**Comment by flyinghead** [comment] 2024-09-07 10:30
I might have a clue as to why disabling the channel causes problems: after AegStep() is called and disables the channel because max attenuation is reached, StreamStep() is still called and will decode one or more samples and increase CA.
One solution would be to test if the channel has been disabled in ChannelEx::Step() and avoid calling other step functions if this is the case:
```diff
                        StepAEG(this);
-                       StepFEG(this);
-                       StepStream(this);
-                       lfo.Step(this);
+                       if (enabled)
+                       {
+                               StepFEG(this);
+                               StepStream(this);
+                               lfo.Step(this);
+                       }
```

Can you test this change? (I'm having a hard time reproducing this issue consistently)

**Comment by kihato** [comment] 2024-09-07 12:27
Awesome!
It worked perfectly fine for #472, #1180 and other issues(#483, #1249, #1030, #1602, #1272) too.

**Comment by flyinghead** [comment] 2024-09-07 13:12
Fixed on master

**Closed** 2024-11-01 13:02 UTC
Labels: bug, audio
