### ISSUE TITLE
Closing the software 

### ISSUE THREAD

**Issue by B-Nerd** [flyinghead/flycast#316] opened 2021-08-12 16:11 UTC
i have a question for a addition for this app is it possible to ad a close button or a option to close the program in the place where you select your roms

**Comment by Gamemulatorer** [comment] 2021-08-13 06:04
Just like Redream there's a exit button.
![Screenshot_2021-08-13-14-03-45-207_io recompiled redream](https://user-images.githubusercontent.com/37603562/129312164-fc7668dd-64cb-4069-bc50-d95e91c31ce0.jpg)

**Comment by B-Nerd** [comment] 2021-08-13 09:07
yep

Verzonden met ProtonMail Mobile

-------- Oorspronkelijk bericht --------
Aan 13 aug. 2021 08:04, Angelo Burgos schreef:

**Comment by flyinghead** [comment] 2021-08-23 08:28
Duplicate of #242

**Closed by flyinghead** 2021-08-23 08:28 UTC
Labels: enhancement, UX
