### ISSUE TITLE
chef's luv shack graphical issues

### ISSUE THREAD

**Issue by AwesumIndustrys** [flyinghead/flycast#511] opened 2022-01-21 02:16 UTC
Platform / OS / Hardware: Ubuntu 20.04

Github hash: I don't know what that is

Hardware: 
Intel Core i5-4300m
Intel HD Graphics 4600
6 GB RAM

**_Description of the Issue_**
Running South Park: Chef's Luv Shack causes the entire game to constantly flicker in OpenGL or have mangled textures in Vulkan.

**_Debugging Steps Tested_**

  * Changing Transparent Sorting setting
  * Changing Copy to VRAM setting
  * Changing from OpenGL to Vulkan and back
  * Enabling and Disabling Delay Frame Swapping

**_Logs Gathered_**

N/A

**_Screenshots_**
https://cdn.discordapp.com/attachments/363848626935431170/933902438124113950/8mb.video-VZr-gTrdEB1A.mp4

**Comment by flyinghead** [comment] 2022-02-14 11:19
`Delay Frame Swapping` is the option that must be set to avoid this flickering.

However it looks like there's been a regression and it now only works with the Vulkan driver. Open GL, DirectX 9 and 11 flicker regardless of the setting.

**Comment by flyinghead** [comment] 2022-02-14 17:50
This should be fixed in the next build

**Closed** 2022-04-30 15:44 UTC
Labels: bug, graphics, regression
