### ISSUE TITLE
Can't play initial d arcade stage ver. 3 Japan (initdv3j)

### ISSUE THREAD

**Issue by kent79** [flyinghead/flycast#1187] opened 2023-09-06 22:14 UTC
Can't play arcade stage ver. 3 Japan (initdv3j). It shows black screen after showing Noami2 logo. But another version (initdv3e) is OK.

**Comment by flyinghead** [comment] 2023-09-07 07:45
duplicate of #647

**Closed by flyinghead** 2023-09-07 07:45 UTC
Labels: bug
