### ISSUE TITLE
Game ID is [DEAD OR ALIVE 2]

### ISSUE THREAD

**Issue by ioamero** [flyinghead/flycast#848] opened 2022-12-31 08:29 UTC
hw/holly/sb.cpp:251 W[HOLLY]: ERROR: Unexpected GD-ROM unlock code: 43a713c5
the game crashes in the preview or attraction mode.

**Comment by flyinghead** [comment] 2022-12-31 15:18
duplicate of #377

**Closed by flyinghead** 2022-12-31 15:18 UTC
