### ISSUE TITLE
Missing texts & invisible objects

### ISSUE THREAD

**Issue by bidinou** [flyinghead/flycast#1391] opened 2024-02-09 09:10 UTC
Platform / OS / Hardware: Android 14 / OpenGL / Samsung A34

Retroarch 1.17.0
libretro-flycast c146a92

**_Description of the Issue_**

Missing texts & invisible objects (sometimes replaced by black boxes)

For instance, the text in the Ikaruga menu, bullets and some objets in Border Down

Another user reported the issue on reddit as well, with screenshots : https://www.reddit.com/r/EmulationOnAndroid/comments/1aijpe2/issue_with_dreamcast_no_text_im_using_flycast/

**_Debugging Steps Tested_**

I tried to enable / disable every single core option

**_Screenshots_**

1st screenshot : missing text
2nd screenshot : invisible bullets

![Screenshot_20240209_100654_RetroArch](https://github.com/flyinghead/flycast/assets/4785199/812e45a4-a93e-47f8-9c6b-3933a8c1693e)

![Screenshot_20240209_100721_RetroArch](https://github.com/flyinghead/flycast/assets/4785199/b68779db-a86d-40e4-8c24-44e21e453f03)

**Comment by flyinghead** [comment] 2024-02-09 09:31
I can't reproduce the issue (RA 1.17 glcore, Nvidia gtx 1080):
![image](https://github.com/flyinghead/flycast/assets/16261910/cd6cff3c-afe0-43ee-867a-9ddeab9d0532)
![image](https://github.com/flyinghead/flycast/assets/16261910/69219cb3-f19c-49e3-878b-13999bcd6467)

It might be a GPU issue but I would recommend testing with a fresh default configuration for both RA and the flycast core. This would rule out any problem due to a configuration option or setting.

**Comment by bidinou** [comment] 2024-02-09 09:57
Hi ! Thank you so much for your prompt reply.
So : I deleted everything ; reinstalled the latest RA & flycast core : same result.
On this same device, I have some quite complex OpenGL & Vulkan apps which work flawlessly (Dolphin for instance).
Take care & thank you so much for your work :-)

**Comment by flyinghead** [comment] 2024-02-09 12:08
This should be fixed in the next master build.
Note that the same issue happens with standalone.

**Comment by bidinou** [comment] 2024-02-09 12:17
Wow, what can I say ! 
Thank you SO MUCH !! :-)
Cheers !

**Closed** 2024-02-17 17:15 UTC
Labels: bug, graphics, regression

**Comment by RafaelOliveira71594** [comment] 2025-07-23 18:01
But That Problem Was Solved And l Have The Same Problem On Here #2020
