### ISSUE TITLE
UI scaling on Steam Deck makes Flycast unusable

### ISSUE THREAD

**Issue by SamusAranX** [flyinghead/flycast#769] opened 2022-10-06 02:43 UTC
Platform / OS / Hardware: Steam Deck

Github hash: b821ece

Hardware: Steam Deck

**_Description of the Issue_**

Just look at the screenshot below. I couldn't find an option that affects UI scaling at all. This is just what Flycast looks like on my Steam Deck. I did not mess with the Steam Deck's default resolution or DPI settings.

**_Screenshots_**

![image](https://user-images.githubusercontent.com/676069/194202302-910e9e39-bc35-4a7d-a883-47e3c35e2de1.png)

**Comment by flyinghead** [comment] 2022-10-06 09:28
How did you install Flycast? Through flathub?

**Comment by SamusAranX** [comment] 2022-10-06 15:29
I installed it through the Discover app. It's a flatpak app.

**Comment by flyinghead** [comment] 2022-10-07 09:15
Can any of you enable logging and post the result here?
You can log to a file (`Settings > Advanced > Log to File` and it will log to flycast.log in the current folder) or simply start it in a terminal:
```
00:00:776 sdl/sdl.cpp:580 N[RENDERER]: Monitor refresh rate: 60 Hz (2560 x 1440)
...
00:00:885 rend/gui.cpp:262 N[RENDERER]: Screen DPI is 96, size 1096 x 823. Scaling by 1.00
```

**Comment by flyinghead** [comment] 2022-10-07 09:18
UI scaling is based on the reported DPI for the screen. I suppose Flycast is being fed a wrong DPI value at startup, which makes it scale the UI by far too much.

**Comment by OutRunner** [comment] 2022-10-08 15:12
Apologies for the delay, here's what I'm getting when run from the command line. As you predicted, that DPI value looks wrong.

```
(127)(deck@steamdeck ~)$ flatpak run org.flycast.Flycast
00:00:414 sdl/sdl.cpp:580 N[RENDERER]: Monitor refresh rate: 60 Hz (1280 x 800)
00:00:436 rend/gui.cpp:262 N[RENDERER]: Screen DPI is 542, size 1280 x 800. Scaling by 4.07
00:00:528 rend/gles/gles.cpp:550 N[RENDERER]: OpenGL version 4.6
00:00:595 oslib/directory.h:304 W[COMMON]: Cannot read directory '/run/media/deck/6435-6638/DC' errno 0x2
```

**Comment by flyinghead** [comment] 2022-10-09 09:39
Yes, 542 DPI is likely wrong. Flycast relies on SDL2 to get this value so the question becomes: why is SDL2 getting a wrong DPI value?
Any idea where this 542 DPI comes from?
It should be around 200 DPI for a 7" screen at 1280x800 resolution.

**Comment by OutRunner** [comment] 2022-10-09 12:38
I’m not entirely certain where 542 is coming from, but if I run xrandr it claims the connected screen is 60mm x 60mm! 😧 Converting 60mm to inches is 2.36 and then dividing 1280 by 2.36 gives 542.372 which looks to be the DPI you’re getting via SDL. xdpyinfo claims the DPI is 96x96 which is obviously not the same. So it seems like the screen or the drivers are mis-reporting its size, so it’s probably a bug for Valve to fix. 

I don’t suppose there’s an ini setting for overriding the DPI?

**Comment by flyinghead** [comment] 2022-10-09 16:09
There's no setting in Flycast to override the DPI or UI scaling, but you might be able to change what's reported by xrandr:
```
xrandr
       --fbmm widthxheight
              Sets  the reported values for the physical size of the screen. Normally, xrandr resets the re‐
              ported physical size values to keep the DPI constant.  This overrides that computation.

       --dpi dpi
              This also sets the reported physical size values of the screen,  it  uses  the  specified  DPI
              value to compute an appropriate physical size using whatever pixel size will be set.
```

**Comment by OutRunner** [comment] 2022-10-09 17:41
I’ve given that a try, I ended up with some comically large text on my terminal screen but thankfully a reboot reset everything. Any values I tried didn’t seem to affect Flycast, and when running it from the command line it still reported the 542dpi value, so despite xrandr being able to change the dpi and screen size it seems SDL2 wasn’t picking that up.

**Comment by vkedwardli** [comment] 2022-10-26 12:27
After some googling the root cause should be incorrect EDID values from your screen, I have fixed it and you may try to override it. 
[SteamDeckEDID.bin.zip](https://github.com/flyinghead/flycast/files/9869187/SteamDeckEDID.bin.zip)

Here's a relevant tutorial:
https://kodi.wiki/view/Archive:Creating_and_using_edid.bin_via_xorg.conf#Configure_xorg_to_read_custom_EDID_file

I guess your connector name is `eDP` (or it could be `eDP-0` or `eDP-1`, use `xrandr --verbose` to check)
```
Option         "ConnectedMonitor" "eDP"
Option         "CustomEDID" "eDP: /home/your-user-name/Downloads/SteamDeckEDID.bin"
Option         "IgnoreEDID" "false"
Option         "UseEDID" "true"
```

if editing `xorg.conf` still cannot override the EDID, you can copy the bin into `/usr/lib/firmware/edid` and force it by kernel command line:
https://wiki.archlinux.org/title/Kernel_mode_setting#Forcing_modes_and_EDID

Editing `/etc/default/grub` and set
`GRUB_CMDLINE_LINUX_DEFAULT="drm.edid_firmware=eDP:edid/SteamDeckEDID.bin"`


YMMV

relevant issues: 
https://github.com/mtkennerly/ludusavi/issues/91#issuecomment-1195878483
https://github.com/rust-windowing/winit/issues/2401

**Comment by flyinghead** [comment] 2022-10-30 12:17
This should now be fixed in Flycast build 0cbf6f6. Re-open this issue if not.

**Comment by ds22x** [comment] 2022-11-03 16:12
Just wanted to chime in and report that, while it scales correctly now in desktop mode, it's still scaling incorrectly when launching Flycast in gaming mode (using the latest Flatpak version c15f446)

Picture below is the console output when launching from terminal through gaming mode (although this doesn't affect the resulting scaling in gaming mode):
![20221103_170802](https://user-images.githubusercontent.com/45218067/199773519-b5728eb5-246e-4d96-b8f2-1b4f7587d83b.jpg)

**Comment by vkedwardli** [comment] 2022-11-03 23:28
@ds22x I guess I wrote the patch based on the Desktop mode environment's EDID (since I don't have the actual device)
But my testing user can launch it in Game Mode without problem also
![giphy8687651638598008666](https://user-images.githubusercontent.com/602245/199854002-f2ed4175-a89d-41ce-8d00-d8d5d96458fa.gif)


Could you share both of your Game Mode and Desktop Mode's xrandr output so I can diagnose what was wrong?

`sudo xrandr --verbose`

**Comment by ds22x** [comment] 2022-11-04 01:45
As requested, the outputs for both desktop and gaming modes, listed at the bottom of this post.
One weird thing I encountered when using xrandr in gaming mode was that it would produce a "Cant open display" error when trying to run it with sudo, but ran fine without it.

<details>
<summary>Desktop</summary>

Screen 0: minimum 320 x 200, current 1280 x 800, maximum 16384 x 16384
eDP connected primary 1280x800+0+0 (0x55) right (normal left inverted right x axis y axis) 60mm x 60mm
        Identifier: 0x52
        Timestamp:  890109
        Subpixel:   unknown
        Gamma:      1.0:1.0:1.0
        Brightness: 1.0
        Clones:
        CRTC:       0
        CRTCs:      0 1 2 3
        Transform:  1.000000 0.000000 0.000000
                    0.000000 1.000000 0.000000
                    0.000000 0.000000 1.000000
                   filter:
        EDID:
                00ffffffffffff0005d8397501000000
                1e1c0104a50605781600000000000000
                00000000000001000100010001000100
                0100010001000f1b204830002c502014
                02043c3c0000001e000000fc00414e58
                3735333020550a202020000000100000
                00000000000000000000000000000010
                00000000000000000000000000000036
        GAMMA_LUT_SIZE: 4096
                range: (0, -1)
        DEGAMMA_LUT_SIZE: 4096
                range: (0, -1)
        GAMMA_LUT: 0
                range: (0, 65535)
        CTM: 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0
                0 1
        DEGAMMA_LUT: 0
                range: (0, 65535)
        TearFree: auto
                supported: off, on, auto
        HDCP Content Type: HDCP Type0
                supported: HDCP Type0, HDCP Type1
        Content Protection: Undesired
                supported: Undesired, Desired, Enabled
        vrr_capable: 0
                range: (0, 1)
        abm level: 0
                range: (0, 4)
        max bpc: 16
                range: (8, 16)
        underscan vborder: 0
                range: (0, 128)
        underscan hborder: 0
                range: (0, 128)
        underscan: off
                supported: off, on, auto
        scaling mode: None
                supported: None, Full, Center, Full aspect
        link-status: Good
                supported: Good, Bad
        CONNECTOR_ID: 82
                supported: 82
        non-desktop: 0
                range: (0, 1)
  800x1280 (0x55) 69.270MHz +HSync +VSync *current +preferred
        h: width   800 start  832 end  852 total  872 skew    0 clock  79.44KHz
        v: height 1280 start 1296 end 1298 total 1324           clock  60.00Hz
  800x600 (0x56) 69.270MHz +HSync +VSync
        h: width   800 start  832 end  852 total  872 skew    0 clock  79.44KHz
        v: height  600 start 1296 end 1298 total 1324           clock  60.00Hz
  640x480 (0x57) 69.270MHz +HSync +VSync
        h: width   640 start  832 end  852 total  872 skew    0 clock  79.44KHz
        v: height  480 start 1296 end 1298 total 1324           clock  60.00Hz
DisplayPort-0 disconnected (normal left inverted right x axis y axis)
        Identifier: 0x53
        Timestamp:  890109
        Subpixel:   unknown
        Clones:
        CRTCs:      0 1 2 3
        Transform:  1.000000 0.000000 0.000000
                    0.000000 1.000000 0.000000
                    0.000000 0.000000 1.000000
                   filter:
        GAMMA_LUT_SIZE: 4096
                range: (0, -1)
        DEGAMMA_LUT_SIZE: 4096
                range: (0, -1)
        GAMMA_LUT: 0
                range: (0, 65535)
        CTM: 0
        DEGAMMA_LUT: 0
                range: (0, 65535)
        TearFree: auto
                supported: off, on, auto
        subconnector: Unknown
                supported: Unknown, VGA, DVI-D, HDMI, DP, Wireless, Native
        HDCP Content Type: HDCP Type0
                supported: HDCP Type0, HDCP Type1
        Content Protection: Undesired
                supported: Undesired, Desired, Enabled
        vrr_capable: 0
                range: (0, 1)
        max bpc: 8
                range: (8, 16)
        underscan vborder: 0
                range: (0, 128)
        underscan hborder: 0
                range: (0, 128)
        underscan: off
                supported: off, on, auto
        scaling mode: None
                supported: None, Full, Center, Full aspect
        link-status: Good
                supported: Good, Bad
        CONNECTOR_ID: 89
                supported: 89
        non-desktop: 0
                range: (0, 1)
</details>

<details>
<summary>Gaming</summary>

Screen 0: minimum 16 x 16, current 1280 x 800, maximum 32767 x 32767
XWAYLAND0 connected 1280x800+0+0 (0x22) normal (normal left inverted right x axis y axis) 60mm x 50mm
        Identifier: 0x21
        Timestamp:  1075931
        Subpixel:   unknown
        Gamma:      1.0:1.0:1.0
        Brightness: 0.0
        Clones:
        CRTC:       0
        CRTCs:      0
        Transform:  1.000000 0.000000 0.000000
                    0.000000 1.000000 0.000000
                    0.000000 0.000000 1.000000
                   filter:
        RANDR Emulation: 1
        non-desktop: 0
                supported: 0, 1
  1280x800 (0x22) 83.500MHz -HSync +VSync *current +preferred
        h: width  1280 start 1352 end 1480 total 1680 skew    0 clock  49.70KHz
        v: height  800 start  803 end  809 total  831           clock  59.81Hz
  1024x768 (0x23) 63.500MHz -HSync +VSync
        h: width  1024 start 1072 end 1176 total 1328 skew    0 clock  47.82KHz
        v: height  768 start  771 end  775 total  798           clock  59.92Hz
  800x600 (0x24) 38.250MHz -HSync +VSync
        h: width   800 start  832 end  912 total 1024 skew    0 clock  37.35KHz
        v: height  600 start  603 end  607 total  624           clock  59.86Hz
  640x480 (0x25) 23.750MHz -HSync +VSync
        h: width   640 start  664 end  720 total  800 skew    0 clock  29.69KHz
        v: height  480 start  483 end  487 total  500           clock  59.38Hz
  320x240 (0x26)  6.000MHz -HSync +VSync
        h: width   320 start  336 end  360 total  400 skew    0 clock  15.00KHz
        v: height  240 start  243 end  247 total  252           clock  59.52Hz
  1152x720 (0x27) 66.750MHz -HSync +VSync
        h: width  1152 start 1208 end 1320 total 1488 skew    0 clock  44.86KHz
        v: height  720 start  723 end  729 total  748           clock  59.97Hz
  960x600 (0x28) 45.250MHz -HSync +VSync
        h: width   960 start  992 end 1088 total 1216 skew    0 clock  37.21KHz
        v: height  600 start  603 end  609 total  624           clock  59.63Hz
  928x580 (0x29) 42.750MHz -HSync +VSync
        h: width   928 start  968 end 1056 total 1184 skew    0 clock  36.11KHz
        v: height  580 start  583 end  589 total  603           clock  59.88Hz
  800x500 (0x2a) 30.750MHz -HSync +VSync
        h: width   800 start  824 end  896 total  992 skew    0 clock  31.00KHz
        v: height  500 start  503 end  509 total  521           clock  59.50Hz
  768x480 (0x2b) 28.750MHz -HSync +VSync
        h: width   768 start  792 end  864 total  960 skew    0 clock  29.95KHz
        v: height  480 start  483 end  489 total  500           clock  59.90Hz
  720x480 (0x2c) 26.750MHz -HSync +VSync
        h: width   720 start  744 end  808 total  896 skew    0 clock  29.85KHz
        v: height  480 start  483 end  493 total  500           clock  59.71Hz
  640x400 (0x2d) 20.000MHz -HSync +VSync
        h: width   640 start  664 end  720 total  800 skew    0 clock  25.00KHz
        v: height  400 start  403 end  409 total  417           clock  59.95Hz
  320x200 (0x2e)  5.000MHz -HSync +VSync
        h: width   320 start  336 end  360 total  400 skew    0 clock  12.50KHz
        v: height  200 start  203 end  209 total  212           clock  58.96Hz
  1280x720 (0x2f) 74.500MHz -HSync +VSync
        h: width  1280 start 1344 end 1472 total 1664 skew    0 clock  44.77KHz
        v: height  720 start  723 end  728 total  748           clock  59.86Hz
  1024x576 (0x30) 46.500MHz -HSync +VSync
        h: width  1024 start 1064 end 1160 total 1296 skew    0 clock  35.88KHz
        v: height  576 start  579 end  584 total  599           clock  59.90Hz
  864x486 (0x31) 32.500MHz -HSync +VSync
        h: width   864 start  888 end  968 total 1072 skew    0 clock  30.32KHz
        v: height  486 start  489 end  494 total  506           clock  59.92Hz
  720x400 (0x32) 22.250MHz -HSync +VSync
        h: width   720 start  744 end  808 total  896 skew    0 clock  24.83KHz
        v: height  400 start  403 end  413 total  417           clock  59.55Hz
  640x350 (0x33) 17.500MHz -HSync +VSync
        h: width   640 start  664 end  720 total  800 skew    0 clock  21.88KHz
        v: height  350 start  353 end  363 total  366           clock  59.77Hz
</details>

**Comment by vkedwardli** [comment] 2022-11-04 09:14
@ds22x thanks for the data

Interesting, in Gaming mode the dimension has changed, and EDID info is missing

Without the EDID data, I cannot patch it, here's a modified Flycast which will show the Display Name in the main screen
 
[flycast-x86_64-pc-linux-gnu_name_check.zip](https://github.com/flyinghead/flycast/files/9936725/flycast-x86_64-pc-linux-gnu_name_check.zip)


Could you run it and do a screen cap?
![image](https://user-images.githubusercontent.com/602245/199936050-d43b9d7a-592c-4a47-9b84-77a62c7f7ff3.png)

**Comment by ds22x** [comment] 2022-11-04 12:12
Here's the screengrab, as requested:
![20221104130636_1](https://user-images.githubusercontent.com/45218067/199969747-68993a57-8ec6-4ec2-99a4-1df1f0612040.jpg)

**Closed** 2022-11-04 15:01 UTC
Labels: bug, UX

**Comment by vkedwardli** [comment] 2022-11-04 16:07
@ds22x you may verify if it is fixed in [605dc59](https://github.com/flyinghead/flycast/commit/605dc59f8dfaabd460c609dd48ac12fd96d55239): https://github.com/flyinghead/flycast/suites/9132557229/artifacts/424322253

**Comment by ds22x** [comment] 2022-11-04 17:07
I think you've linked to the wrong artifact, as the one you've linked contains a Libretro .so core file.

**Comment by vkedwardli** [comment] 2022-11-04 17:09
@ds22x oops, sorry, link updated

**Comment by ds22x** [comment] 2022-11-04 17:15
Okay, can confirm it has been fixed.
