### ISSUE TITLE
MacOS, tying to run Virtua Tennis on Naomi (0.224 Mame version) the emulator always exit after 10-12 seconds

### ISSUE THREAD

**Issue by aminta** [flyinghead/flycast#109] opened 2020-08-31 14:12 UTC
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware:  MacBook Pro 15" 2017 / MacOS Catalina 10.15.6 

Github hash: 

Hardware: Naomi

**_Description of the Issue_**

Trying to run Virtua Tennis on Naomi (0.224 Mame version) the emulator always exit after 10-12 seconds, no matter what you do. Tried with many Flycast build from march to august 2020.

Add a short, concise description of the issue here

**_Debugging Steps Tested_**

  * Fill in any steps already tried here
  * Begin each new line with an asterisk
  * If no steps are required, please skip

**_Logs Gathered_**

https://pastebin.com/1V0ibREG

**_Screenshots_**

(Replace this line with any issue screenshots)

**Comment by flyinghead** [comment] 2020-08-31 20:01
Duplicate of #92

**Closed by flyinghead** 2020-08-31 20:01 UTC
Labels: duplicate
