### ISSUE TITLE
[arm32] Soulcalibur & Sword of berserk animation glitches

### ISSUE THREAD

**Issue by SpeedemoN1** [flyinghead/flycast#556] opened 2022-03-05 13:06 UTC
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: andriod vulkan/opengl3.2

Github hash:

Hardware:
PvrGE8320 helio g25 32bits 2gb ram 32gbrom

Issue description
Animation glitches that looks sweet

* screenshots*
![Screenshot_2022-03-05-17-48-12-067_com flycast emulator](https://user-images.githubusercontent.com/100472534/156884216-6bb12ab0-1ddb-4d31-a0a2-d858dbe784c2.jpg)
![Screenshot_2022-03-05-21-00-54-065_com google android youtube](https://user-images.githubusercontent.com/100472534/156884217-61a9a54c-f6cb-48b2-99a5-9efa2c10cb70.jpg)

**Comment by flyinghead** [comment] 2023-01-23 14:27
I can't reproduce this on a PowerVR GE8300 and I don't have a GE8320 to test with.

Is this still happening?
What's the version of your driver? (Settings > About > OpenGL)

**Comment by flyinghead** [comment] 2023-07-11 07:23
assuming this is fixed

**Comment by flyinghead** [comment] 2023-10-24 17:43
This looks like a floating point rounding issue. I can reproduce it on x64 by ignoring the SH4 rounding mode.
However this always happen on arm32 platforms, including running 32-bit code on aarch64.
Advanced SIMD instructions ignore the rounding mode (always round to nearest) but "almost" all VFP instructions honor it. The dynarec normally only uses VFP instructions when rounding is involved.
This isn't a regression (reicast has the same issue).

**Comment by flyinghead** [comment] 2023-10-25 15:32
Should be fixed in the latest master build.
For some reason the CPU rounding mode wasn't set on arm32 android.

**Comment by flyinghead** [comment] 2023-10-26 08:20
Fixed for good this time

**Closed by flyinghead** 2023-10-26 08:20 UTC
Labels: bug
