### ISSUE TITLE
[Pixel 7 / Mali-G710 MP7] Flickering screen with per pixel-sorting on Android

### ISSUE THREAD

**Issue by etrav** [flyinghead/flycast#1234] opened 2023-10-10 04:58 UTC
Platform / OS / Hardware: Android 13 / Pixel 7

Github hash: 

Hardware: Pixel 7

**_Description of the Issue_**

When using Vulkan with per-pixel sorting, the screen has weird artifact flashing/flickering in the top left quarter in all games. Essentially, it looks the same as here 
https://github.com/flyinghead/flycast/issues/1014
Seems to be the same issue. I am using the latest stable build of Flycast for Android.
How can this be solved?

**_Debugging Steps Tested_**

  * tried switching on and off all possible video settings
  * tried changing resolution
  * tried changing the values for the buffer and number of layers

**_Logs Gathered_**

**_Screenshots_**

Same as here
https://github.com/flyinghead/flycast/issues/1014

**Comment by flyinghead** [comment] 2023-10-10 07:12
This is very likely a GPU or GPU driver issue. Try to update your firmware/drivers if possible.

**Comment by etrav** [comment] 2023-10-10 09:43
My phone has the latest firmware/Android installed, I cannot update anything. How can I reinstall the graphics driver on Android?

**Comment by etrav** [comment] 2023-10-10 10:16
So, maybe it is a general issue flycast has with Mali-GPUs and not a bug related to specific driver problem?

**Comment by flyinghead** [comment] 2023-10-10 11:03
Well, the Vulkan per pixel renderer works on most GPUs. It conforms to the Vulkan specifications and passes the validation layers without error.
Some GPUs do have issues with it though, particularly on mobile, including some recent and powerful ones. Issues include crashes, black screens and less severe glitches. My investigations into some of them have always led to a non-conformant Vulkan driver.
But you have any insight into what the problem is or how to work around it, I'm all ears.

**Comment by etrav** [comment] 2023-10-10 11:26
I see. Well, sadly I am not a dev so I have no clue where the error might be coming from. However, I just made an interesting observation: when enabling "full framebuffer emulation" this flickering disappears entirely. So, maybe you could have a look what is done differently with "full framebuffer emulation" on and deduce the source of the error.

**Comment by flyinghead** [comment] 2023-10-10 12:50
Interesting. The main difference is the rendering cycle. With "Full Framebuffer Emulation" the rendered frame is copied back to VRAM. Then read again from VRAM and displayed. In order to do that, Flycast has to wait for the GPU to finish rendering before it can read the frame back.
No such wait is needed without Full FB Emulation and adding one would have a serious impact on performance. But there might be other synchronization mechanisms that could be used instead.

**Comment by flyinghead** [comment] 2023-10-11 08:01
My first attempt at adding a sync event to fix this issue resulted in a phone instant reboot (!) I had never experienced that before.
Anyway, I tweaked the event parameters and it doesn't crash my test phone anymore and seems to help with the per pixel glitches.
Please try the latest master build and report.

**Comment by etrav** [comment] 2023-10-11 11:40
Thanks for the effort. Now the emulator freezes right after the start with per pixel sorting. It works as before with per triangle/per strip. Would a log help you? Where can I find it?

**Comment by flyinghead** [comment] 2023-10-11 12:11
No, stuff happening on the GPU can't be logged or debugged. This change has been successfully tested on linux desktop (Nvidia GTX1080) and android (Mali G-51) and passes the vulkan validation layers. So there's really an issue with Mali drivers or GPU here.

I'll revert the change.

**Comment by flyinghead** [comment] 2024-02-27 17:53
Closing since it's a driver issue and no workaround has been found.

**Closed** 2024-02-27 17:53 UTC
Labels: graphics

**Comment by VoidPaul** [comment] 2025-02-21 02:14
For future readers, my Samsung A22—which also uses a Mali GPU (Mali-G52 MC2)—, also faces this issue when using per pixel sorting. This seems to be truly an issue with Mali GPUs in general. That, or Samsung and Honor don't know how to make a driver.

**Comment by FATCatAndroid12** [comment] 2025-03-07 06:47
Might be good to report this driver bug issue here
https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues???

**Comment by FATCatAndroid12** [comment] 2025-03-07 08:16
Might be a good idea to add a text info beside per pexil setting that enable this option can cause graphical issue on mali gpu

![Image](https://github.com/user-attachments/assets/42e92250-d543-4d8e-991f-d67f7213eda7)

**Comment by FATCatAndroid12** [comment] 2025-03-11 00:09
If i increase the per pixel buffer to 1gb it can result to a crash! 

´´´ 01:49:597 rend/vulkan/oit/oit_renderer.cpp:32 N[RENDERER]: OITVulkanRenderer::Init
01:51:831 audio/audiobackend_oboe.cpp:122 N[AUDIO]: Oboe driver started. stream capacity: 2048 frames, size: 512 frames, frames/callback: 512, frames/burst: 256
02:32:876 audio/audiobackend_oboe.cpp:129 N[AUDIO]: Oboe driver stopping
02:46:621 audio/audiobackend_oboe.cpp:122 N[AUDIO]: Oboe driver started. stream capacity: 2048 frames, size: 512 frames, frames/callback: 512, frames/burst: 256
00:00:000 rend/vulkan/vulkan_context.cpp:269 N[RENDERER]: Vulkan API 1.1. Device Mali-G52
00:00:009 rend/vulkan/vulkan_context.cpp:423 N[RENDERER]: Device extension enabled: VK_KHR_swapchain
00:00:009 rend/vulkan/vulkan_context.cpp:426 N[RENDERER]: Device extension unavailable: VK_KHR_portability_subset
00:00:009 rend/vulkan/vulkan_context.cpp:426 N[RENDERER]: Device extension unavailable: VK_EXT_provoking_vertex
00:00:038 rend/vulkan/vulkan_context.h:326 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:00:177 ui/gui.cpp:331 N[RENDERER]: Screen DPI is 395, size 2240 x 980. Scaling by 2.96
00:00:178 rend/vulkan/oit/oit_renderer.cpp:32 N[RENDERER]: OITVulkanRenderer::Init
00:00:700 rend/vulkan/vulkan_context.h:326 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:00:719 rend/vulkan/vulkan_context.cpp:269 N[RENDERER]: Vulkan API 1.1. Device Mali-G52
00:00:719 rend/vulkan/vulkan_context.cpp:423 N[RENDERER]: Device extension enabled: VK_KHR_swapchain
00:00:720 rend/vulkan/vulkan_context.cpp:426 N[RENDERER]: Device extension unavailable: VK_KHR_portability_subset
00:00:720 rend/vulkan/vulkan_context.cpp:426 N[RENDERER]: Device extension unavailable: VK_EXT_provoking_vertex
00:00:867 rend/vulkan/vulkan_context.h:326 N[RENDERER]: Using depth format D32SfloatS8Uint tiling Optimal
00:00:879 rend/vulkan/oit/oit_renderer.cpp:32 N[RENDERER]: OITVulkanRenderer::Init ˋˋˋ
