### ISSUE TITLE
[POCO X6 Android 14] Taps don't respond at all.

### ISSUE THREAD

**Issue by MCat13** [flyinghead/flycast#1421] opened 2024-02-24 05:42 UTC
Platform/OS/Hardware:
android
xiaomi HyperOS 1.0.4.0(android14)
xiaomi POCO X6 Pro 5G

Github hash:v2.2-170-g67c4e62c5

**_Explanation about this matter_**

The app can be launched without any problems, but after that, it does not accept any taps on the screen and cannot be operated at all.

**_Tested debugging steps_**

* Reinstall the app
* Restart your smartphone

**Comment by flyinghead** [comment] 2024-02-27 11:09
I do not own this phone, or any phone running Android 14.
However I tested a Pixel 6a with android 14 in the Android Simulator and couldn't reproduce this issue.

**Comment by MCat13** [comment] 2024-02-28 05:20
Thank you for verifying.

**Comment by flyinghead** [comment] 2024-06-21 20:24
Similar issue with a Samsung A34 running android 14

**Comment by flyinghead** [comment] 2024-06-23 09:32
Should be fixed in the latest `master` build

**Closed** 2024-10-18 14:31 UTC
Labels: bug
