### ISSUE TITLE
Some games have map error with some grahics API 

### ISSUE THREAD

**Issue by leoxxx** [flyinghead/flycast#635] opened 2022-05-16 01:33 UTC
https://github.com/blueminder/flycast-dojo/issues/19

**Comment by flyinghead** [comment] 2022-05-16 07:46
https://github.com/flyinghead/flycast/issues/570#issuecomment-1124905524

**Comment by flyinghead** [comment] 2022-05-29 10:44
Duplicate of #570

**Closed by flyinghead** 2022-05-29 10:44 UTC
Labels: bug

**Comment by leoxxx** [comment] 2022-09-10 07:08
https://github.com/flyinghead/flycast/issues/570#issuecomment-1242650190
Still error.
I think it's not a Duplicate of https://github.com/flyinghead/flycast/issues/570
