### ISSUE TITLE
Duplicate frame For Flycast and libretro core

### ISSUE THREAD

**Issue by jeremy27041980** [flyinghead/flycast#624] opened 2022-05-05 20:16 UTC
Hi,

Could you add this feature to flycast ?

30 fps games like Skies of Arcadia are very choppy but if i turn my TV refresh rate to 30 hertz, problem is solve but latency is horrible.

60 fps games are smooth.

Thanks for your great work for this emulator !

**Comment by flyinghead** [comment] 2022-05-05 20:23
duplicate of #520

**Closed by flyinghead** 2022-05-05 20:23 UTC
Labels: duplicate
