### ISSUE TITLE
Feature request: Option to adjust size of VMU display on screen

### ISSUE THREAD

**Issue by banana3333** [flyinghead/flycast#1317] opened 2023-11-23 22:28 UTC
**Describe the solution you'd like**
Maybe a couple preset size options for the VMU display? Specifically wanting ones to make it smaller. Options to select where it appears would be cool as well, such as the ability to place it within the pillarbox bars when playing on a 16:9 display or something. The ability to simply adjust the size is the big thing, though.

**Is your feature request related to a problem? Please describe.**
For whatever reason, the Flycast UI is gigantic on my device (Powkiddy X28, uses same T618 SoC as other handhelds like the Retroid Pocket 3+ or RG405m), and the the VMU display has ballooned up with it. I've used Flycast on various Retroid devices before including the RP3+, so I know it's thankfully not actually supposed to look like this .

**Additional context**

You can see how massive it displays here. The ability to display it at half this height and width, just as an example, would be great.
![Screenshot_20231116-105222](https://github.com/flyinghead/flycast/assets/66152283/46ae53e0-411d-4d88-b918-1347716aad5f)

If you're curious about how the UI displays on my device since I mentioned it's extremely large, here are some screenshots of that.

![Screenshot_20231123-161130](https://github.com/flyinghead/flycast/assets/66152283/d25349a0-04d0-4d4c-bcf0-3568f687b142)
![Screenshot_20231123-161138](https://github.com/flyinghead/flycast/assets/66152283/5e71452e-aca6-4285-be02-06b949d3c757)
![Screenshot_20231123-161339](https://github.com/flyinghead/flycast/assets/66152283/56911266-2137-4410-9da4-84b76e874a5e)

**Comment by vkedwardli** [comment] 2023-11-24 00:59
Is it an Android handheld? Looks like it is reporting a wrong screen resolution/dimension

**Comment by flyinghead** [comment] 2023-11-24 08:09
Yes, the DPI and/or dimensions of the screen reported by the OS are obviously wrong.

I recently added a setting to scale up or down the UI on the `dev` branch:
![image](https://github.com/flyinghead/flycast/assets/16261910/a21e5017-4b34-4416-9cb8-f233343d86c0)

You should give it a try.

**Comment by flyinghead** [comment] 2023-11-26 16:53
Duplicate of #162

**Closed by flyinghead** 2023-11-26 16:53 UTC
Labels: enhancement
