### ISSUE TITLE
Densha De Go! 2 unplayable due to broken HUD

### ISSUE THREAD

**Issue by TreeBranches** [flyinghead/flycast#171] opened 2021-02-04 11:12 UTC
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 
Windows 10 and Xbox Series X

Flycast 0.1 ea1278e

Hardware: 
Ryzen 5 2600
NVidia GeForce 1080ti
32GB RAM

**_Description of the Issue_**

The HUD is missing most elements, causing the game to be unplayable.

**_Screenshots_**

Three screenshots of the initial menu's and the gameplay: https://i.imgur.com/hZL2Xaf.png

This is a video of how the HUD is supposed to look: https://youtu.be/Ic0UAVTQUrc?t=737

Game Option File:
```reicast_allow_service_buttons = "enabled"
reicast_alpha_sorting = "per-pixel (accurate)"
reicast_analog_stick_deadzone = "15%"
reicast_anisotropic_filtering = "4"
reicast_boot_to_bios = "disabled"
reicast_broadcast = "Default"
reicast_cable_type = "TV (RGB)"
reicast_custom_textures = "disabled"
reicast_delay_frame_swapping = "disabled"
reicast_digital_triggers = "disabled"
reicast_div_matching = "auto"
reicast_dump_textures = "disabled"
reicast_enable_dsp = "enabled"
reicast_enable_naomi_15khz_dipswitch = "disabled"
reicast_enable_purupuru = "enabled"
reicast_enable_rttb = "disabled"
reicast_fog = "enabled"
reicast_force_wince = "enabled"
reicast_frame_skipping = "disabled"
reicast_framerate = "fullspeed"
reicast_gdrom_fast_loading = "disabled"
reicast_hle_bios = "disabled"
reicast_internal_resolution = "640x480"
reicast_language = "Default"
reicast_lightgun1_crosshair = "disabled"
reicast_lightgun2_crosshair = "disabled"
reicast_lightgun3_crosshair = "disabled"
reicast_lightgun4_crosshair = "disabled"
reicast_mipmapping = "enabled"
reicast_oit_abuffer_size = "512MB"
reicast_per_content_vmus = "disabled"
reicast_pvr2_filtering = "disabled"
reicast_region = "Default"
reicast_render_to_texture_upscaling = "1x"
reicast_screen_rotation = "horizontal"
reicast_show_lightgun_settings = "enabled"
reicast_show_vmu_screen_settings = "disabled"
reicast_synchronous_rendering = "enabled"
reicast_system = "auto"
reicast_texupscale = "off"
reicast_texupscale_max_filtered_texture_size = "256"
reicast_threaded_rendering = "disabled"
reicast_trigger_deadzone = "0%"
reicast_vmu1_pixel_off_color = "DEFAULT_OFF 01"
reicast_vmu1_pixel_on_color = "DEFAULT_ON 00"
reicast_vmu1_screen_display = "disabled"
reicast_vmu1_screen_opacity = "100%"
reicast_vmu1_screen_position = "Upper Left"
reicast_vmu1_screen_size_mult = "1x"
reicast_vmu2_pixel_off_color = "DEFAULT_OFF 01"
reicast_vmu2_pixel_on_color = "DEFAULT_ON 00"
reicast_vmu2_screen_display = "disabled"
reicast_vmu2_screen_opacity = "100%"
reicast_vmu2_screen_position = "Upper Left"
reicast_vmu2_screen_size_mult = "1x"
reicast_vmu3_pixel_off_color = "DEFAULT_OFF 01"
reicast_vmu3_pixel_on_color = "DEFAULT_ON 00"
reicast_vmu3_screen_display = "disabled"
reicast_vmu3_screen_opacity = "100%"
reicast_vmu3_screen_position = "Upper Left"
reicast_vmu3_screen_size_mult = "1x"
reicast_vmu4_pixel_off_color = "DEFAULT_OFF 01"
reicast_vmu4_pixel_on_color = "DEFAULT_ON 00"
reicast_vmu4_screen_display = "disabled"
reicast_vmu4_screen_opacity = "100%"
reicast_vmu4_screen_position = "Upper Left"
reicast_vmu4_screen_size_mult = "1x"
reicast_volume_modifier_enable = "enabled"
reicast_widescreen_cheats = "disabled"
reicast_widescreen_hack = "disabled"

**Comment by flyinghead** [comment] 2021-02-07 17:25
I can easily reproduce the issue. It doesn't seem to be a depth issue or a graphics glitch as the missing geometry isn't sent to the GPU. I haven't found any workaround.

Note that this is the github for standalone flycast. The libretro core github is at https://github.com/libretro/flycast.
However since this issue also affects standalone, there's no need to move this issue.

**Comment by superblobster** [comment] 2022-05-02 02:12
This bug is unfortunately still present :(

![Screenshot 2022-05-02 050437](https://user-images.githubusercontent.com/60817163/166176388-3e725d3f-a2ce-4520-991f-c00e6784f5f0.png)

**Comment by flyinghead** [comment] 2022-10-23 15:34
I pushed a fix for this issue on the `dev` branch.

**Comment by superblobster** [comment] 2022-10-23 16:42
Yup, it's working now :)

![Screenshot 2022-10-23 194042](https://user-images.githubusercontent.com/60817163/197404474-1b2c0a76-5630-4efe-b07d-b25c22b0499f.png)

**Closed** 2023-01-17 08:46 UTC
Labels: bug
