### ISSUE TITLE
Initial D Arcade Stage Ver. 3 (Japan) black screen

### ISSUE THREAD

**Issue by Tatsuya79** [flyinghead/flycast#887] opened 2023-01-20 10:20 UTC
Platform / OS / Hardware: libretro win10 x64 vulkan

Github hash: cca7ed6

Hardware: ryzen 5600X nvidia 1650

**_Description of the Issue_**

**Initial D Arcade Stage Ver. 3 (Japan) (Rev C) (GDS-0032C)**
stays on a black screen after starting to load the game and showing "clean up the card".

**_Debugging Steps Tested_**

I forced "Japan" in the bios selection as I saw it wasn't auto detected in the log but no difference.
Everything is MAME 0.251, roms, bios and chd.

Then I went with 
Initial D Arcade Stage Ver. 3 (Export) (GDS-0033)
which is working fine.

I got rid of the Japanese chd now, so sorry I can't test anymore but just wanted to let you know about that.
Thanks for that great emu which progressed so much. 👍

**Comment by flyinghead** [comment] 2023-01-20 10:53
Yes it's a known issue with the Japanese version.
Duplicate of #647

**Closed by flyinghead** 2023-01-20 10:53 UTC
Labels: bug
