### ISSUE TITLE
Wild Riders (NAOMI 2) Transition effects are broken, multiple lines during textures on Per Pixel

### ISSUE THREAD

**Issue by TheCoolPup** [flyinghead/flycast#1387] opened 2024-02-06 21:14 UTC
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

Platform / OS / Hardware: 

Github hash: e592650

Hardware: Windows 11, AMD Ryzen 5600H @3.3GHz, Nvidia RTX 3050ti Laptop GPU

Some transition effects are broken, and many lines can be seen through effects/textures on per pixel, does not happen on per pixel.

**Comment by flyinghead** [comment] 2024-02-07 10:23
I'm not seeing any obvious issue. Can you post a screenshot?
If this is a regression, can you try older builds on the `dev` branch to find out when the problem started?

**Comment by TheCoolPup** [comment] 2024-02-07 17:57
https://github.com/flyinghead/flycast/assets/91135037/fffa6a02-1d82-420e-a5cd-2ddd7195a7c3

normally for example, right here its supposed to fade to black

**Comment by flyinghead** [comment] 2024-02-07 18:01
Is this a regression?
Please upload a savestate so I can test this transition.

**Comment by TheCoolPup** [comment] 2024-02-07 18:07
[wldrider savestate.zip](https://github.com/flyinghead/flycast/files/14199887/wldrider.savestate.zip)
same bub also happens during the ending

**Comment by flyinghead** [comment] 2024-02-08 17:16
I see the book closing and the scene fades to black at this point.
Can you spot another issue?

**Comment by TheCoolPup** [comment] 2024-02-08 18:44
https://github.com/flyinghead/flycast/assets/91135037/04f0a0c6-48c7-4e6f-83e8-85a2a0edd228


https://github.com/flyinghead/flycast/assets/91135037/6faefcfc-eda6-4e8c-99a3-35c9164b677b

the same bug happens at the end of the character select, normally the background is supposed to stay white but it turns black, happens when the 3d models of trish or keith appear

**Comment by flyinghead** [comment] 2024-02-08 18:54
I can't reproduce it here. Tried OpenGL and Vulkan renderers. The background stays white.

Which renderer are you using? Does it make a difference?

**Comment by flyinghead** [comment] 2024-02-27 08:44
Can't reproduce

**Closed** 2024-02-27 08:44 UTC
