### ISSUE TITLE
[Retroarch] Resident Evil Code Veronica jumps from 30 fps to 60 when switching from windowed to fullscreen

### ISSUE THREAD

**Issue by eddlang** [flyinghead/flycast#321] opened 2021-08-16 17:01 UTC
Windows 10 64-bit
Ryzen 2600
Geforce GTX 1060 6GB
60Hz monitor
vsync enabled in retroarch
glcore

I'm using flycast 1.0-159-g8b0f17fb (flycast-libretro-x86_64-w64-mingw32) with retroarch 1.9.7 64-bit.

When I launch Resident Evil Code Veronica in either windowed or fullscreen mode, the fps is fine, set to 30.
If I launch it windowed and then switch to fullscreen, the fps jumps to 60, game runs at double speed and the audio is lost.

Happens with both exclusive and windowed fullscreen. Switching back to windowed doesn't fix it. I have to close the game to fix it, and sometimes even need to restart retroarch.

**Comment by bslenul** [comment] 2021-08-17 10:25
I can reproduce but randomly, idk if it's the same for you but it doesn't necessarily happen on the first switch:

https://user-images.githubusercontent.com/33353403/129709729-bf3fd42a-76af-4741-a657-664eafcdf492.mp4

It doesn't seem to happen with `Quick Menu > Options > Threaded Rendering` OFF however.

**Comment by flyinghead** [comment] 2021-08-22 16:04
My guess is that the audio is sometimes lost when toggling fullscreen/window. (RetroArch resets all drivers when switching.) So Flycast looses its main source of synchronization. Since this is a 30 FPS game, it's no longer limited and runs twice as fast.

@bslenul Do you have anything in the log for the savestate issue? I tried to reproduce the problem a couple of times without success.

**Comment by bslenul** [comment] 2021-08-22 16:16
https://pastebin.com/2tmJsW7b

Line 144 it loads fine:

> [INFO] [State]: Loading state "D:\programmes\RetroArch\states\Crazy Taxi (USA).state", 36609480 bytes.
[libretro WARN] core\emulator.cpp:716 W[SAVESTATE]: Savestate: loaded 36609453 bytes but used 28273797

I close content, restart the game, then it failed, line 356:

> [INFO] [State]: Loading state "D:\programmes\RetroArch\states\Crazy Taxi (USA).state", 36609480 bytes.
[ERROR] [State]: Failed to load state from "D:\programmes\RetroArch\states\Crazy Taxi (USA).state".

The weird thing is that from the logs, it's trying to load the state after the core was closed 🤔

**Comment by bslenul** [comment] 2021-08-22 17:20
Can't seem to reproduce on my Linux VM on load state, however when saving state it closes content as well: https://pastebin.com/gqZr8h0r

Line 152, the state file doesn't exist yet and it just says that:
```
[INFO] [Environ]: SHUTDOWN.
```
Then I launch the game again, and re-create the state, and this time I get this (line 315):
```
[INFO] [State]: File already exists. Saving to backup buffer ...
[INFO] [State]: Loading state "/home/bobby/.config/retroarch/states/Ikaruga (Japan).state", 36609480 bytes.
[INFO] [Environ]: SHUTDOWN.
```

**Comment by flyinghead** [comment] 2021-08-22 18:17
The savestate issue is probably a side effect of a recent change. I'll push a fix for it.

I don't think it's related to the original issue however.

**Comment by flyinghead** [comment] 2021-08-22 18:42
The savestate problem should be fixed by https://github.com/flyinghead/flycast/commit/7fb83f4f7716aa9ccfd5084d0b59b81fc62f605d.

**Comment by bslenul** [comment] 2021-08-22 22:41
No change unfortunately :( If it's not related, do you want me to open a new issue for this?

**Comment by flyinghead** [comment] 2021-08-23 06:31
Probably best to open a new issue then. And yes, this is the change I was referring to.

can you also attach new log to the issue? Thanks

**Closed** 2022-04-30 10:25 UTC
Labels: audio, libretro
