### ISSUE TITLE
Add hotkeys for save and load savestates

### ISSUE THREAD

**Issue by BCGamerYT** [flyinghead/flycast#615] opened 2022-05-01 03:11 UTC
**Is your feature request related to a problem? Please describe.**
- Pressing combined keys between left-shift and function key to savestate.

**Describe the solution you'd like**
- I have tried to slow way to savestate while pressing menu and savestate.

**Describe alternatives you've considered**

**Additional context**

**Comment by kathyrollo** [comment] 2022-07-21 09:39
Seconding hotkey support. Extremely useful in lightgun games using a gaming mouse with extra mappable side buttons.

**Comment by Shideravan** [comment] 2022-09-01 19:35
Would be nice if this shortcut are configurable too. eg.: I like to put the savestate/loadstate in controller buttons L1/R1

**Comment by blueminder** [comment] 2022-09-01 21:17
FWIW, this feature exists in Flycast Dojo's Training Mode:
https://github.com/blueminder/flycast-dojo

**Comment by PiperCalls** [comment] 2022-10-04 20:14
Yes would like this feature as well.

**Comment by flyinghead** [comment] 2023-03-01 21:14
available on the dev branch

**Comment by anonyme-x22** [comment] 2023-03-30 12:20
Hi,
Also seconding.
Please also add hard /soft (don't know if soft apply) reset , slot +/-

Thanks in advance,
Have a good day,
rgds,

**Comment by Leafdomain** [comment] 2023-04-17 22:23
@flyinghead
Tested the feature. It works amazingly. Thank you so much for adding this!

I was wondering, would it be possible to add an assignable button for going fullscreen as well?
In many programs and especially emulators, F11 is the common button for going fullscreen, so some people understandably prefer it that way. It would be awesome if we could also assign this as the user desires. Or just adding F11 as an alternative alongside alt+Enter would be more than fine too. Cemu did it that way when I suggested it. Please consider, many people would appreciate the addition of this too.

Again thank you so much for the hotkeys for save state and load state. It's awesome and extremely useful, it was a very important qol feature to be added. Many people will be very grateful.
Cheers.

**Comment by Enkak** [comment] 2023-05-06 21:26
I can confirm that is working great here too. 

Is it possible to add also hotkeys for decreasing and increasing the save state slot? That way it would not overwrite always slot number 1 and would be great for cases like when using RocketLauncher Pause Menu where we can choose there what slot to save or load with visual cues and time of save.

**Comment by anonyme-x22** [comment] 2023-05-07 19:27
Hi,
I have the 5f161df on linux don't see any mapping for load and save snapshot?
Thanks in advance,
Have a good day,
Rgds,

**Comment by flyinghead** [comment] 2023-05-07 19:31
> available on the dev branch

not on master yet

**Closed** 2023-05-30 13:51 UTC
Labels: enhancement, good first issue

**Comment by kathyrollo** [comment] 2023-05-30 16:51
I haven't updated since v2.1 from the Releases page but this should be a good reason. Thank you @flyinghead !

**Comment by Leafdomain** [comment] 2023-06-06 12:34
Alright
