### ISSUE TITLE
(NAOMI) Shin Nihon Pro Wrestiling Toukon Restuden 4 Arcade Edition Attract mode FMV fails to load 

### ISSUE THREAD

**Issue by TheCoolPup** [flyinghead/flycast#1582] opened 2024-07-16 12:27 UTC
Platform / OS / Hardware: AMD Ryzen 5600H @3.3Ghz Windows 11 Nvidia RTX 3050ti Laptop GPU 16gb RAM

Github hash: 2a4356e

After the first gameplay demo, a fmv starts to play but it freezes and goes back to the title screen.

![Flycast - Shin Nihon Pro Wrestling Toukon Retsuden 4 Arcade Edition (Japan, TRF1 Ver A) 7_16_2024 8_27_09 AM](https://github.com/user-attachments/assets/1a3ad56c-8719-42eb-b87f-5f00025f3c05)

**Comment by flyinghead** [comment] 2024-07-16 16:31
regression due to 7cc77b10ed5e59db42947128d8715ff415bbe8d7

**Comment by flyinghead** [comment] 2024-07-17 08:33
Fixed on master

**Closed** 2024-08-01 19:45 UTC
Labels: bug, regression
