### ISSUE TITLE
Is there a plan to upgrade targetSdk to 33 for Android

### ISSUE THREAD

**Issue by hsoftxl** [flyinghead/flycast#1075] opened 2023-05-22 11:06 UTC
Is there a plan to upgrade targetSdk to 33

**Comment by flyinghead** [comment] 2023-05-22 12:03
No. Why?

**Comment by vkedwardli** [comment] 2023-05-22 15:41
Duplicate of https://github.com/flyinghead/flycast/issues/914?

**Closed** 2023-05-25 02:51 UTC
Labels: enhancement
