### ISSUE TITLE
Add a GUI for Flycast

### ISSUE THREAD

**Issue by enma09art** [flyinghead/flycast#499] opened 2022-01-07 02:51 UTC
Add a GUI with the box art of the games like other emulators in the future.

Ex:
![EA002374-1DA0-49BF-A873-9614543FFBE3](https://user-images.githubusercontent.com/87793814/148483495-830c7fc7-3566-453e-9c41-7f7fd921b63d.jpeg)
![F1DF54BF-27DB-452F-B158-D7433048664C](https://user-images.githubusercontent.com/87793814/148483575-f8283bb2-01a7-44ad-817e-b3fff38cd95e.jpeg)
![4A123400-CF91-49DF-B8B1-F309E864C91B](https://user-images.githubusercontent.com/87793814/148483701-f4c3b889-0bf3-4b52-b94e-5b312629144d.png)

**Comment by vkedwardli** [comment] 2022-01-07 06:02
duplicate of https://github.com/flyinghead/flycast/issues/22

**Comment by flyinghead** [comment] 2022-01-07 08:13
See issue #22

**Closed by flyinghead** 2022-01-07 08:13 UTC
Labels: enhancement
