### ISSUE TITLE
Failure during linking when building Libretro Switch core

### ISSUE THREAD

**Issue by aitorciki** [flyinghead/flycast#1098] opened 2023-06-03 12:25 UTC
Platform / OS / Hardware: Nintendo Switch 
Github hash: bc3c1ab6
Hardware: building on AMD64 Windows + MSYS2 or Ubuntu

Trying to build a libretro core for Nintendo Switch following [these steps](https://docs.libretro.com/development/retroarch/compilation/switch-libnx/) fails during linking of the RetroArch binary with the core. Flycast core builds correctly, RetroArch builds correctly, but linking fails due to undefined references (notably to CMakeRC resources):

```
$ make -f Makefile.libnx
linking retroarch_switch.elf
/opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/13.1.0/../../../../aarch64-none-elf/bin/ld: /opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/13.1.0/../../../../aarch64-none-elf/bin/ld: DWARF error: can't find .debug_ranges section.
libretro_libnx.a(printer.o): in function `printer::BitmapWriter::BitmapWriter(int)':
printer.cpp:(.text._ZN7printer12BitmapWriterC2Ei[_ZN7printer12BitmapWriterC5Ei]+0x64): undefined reference to `cmrc::flycast::get_filesystem()'
/opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/13.1.0/../../../../aarch64-none-elf/bin/ld: /opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/13.1.0/../../../../aarch64-none-elf/bin/ld: DWARF error: can't find .debug_ranges section.
libretro_libnx.a(reios.o): in function `reios_reset(unsigned char*)':
reios.cpp:(.text._Z11reios_resetPh+0x9c): undefined reference to `cmrc::flycast::get_filesystem()'
/opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/13.1.0/../../../../aarch64-none-elf/bin/ld: /opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/13.1.0/../../../../aarch64-none-elf/bin/ld: DWARF error: can't find .debug_ranges section.
libretro_libnx.a(reios_elf.o): in function `reios_loadElf(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
reios_elf.cpp:(.text._Z13reios_loadElfRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0xa4): undefined reference to `elf_newFile'
/opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/13.1.0/../../../../aarch64-none-elf/bin/ld: reios_elf.cpp:(.text._Z13reios_loadElfRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0xe0): undefined reference to `elf_checkFile'
/opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/13.1.0/../../../../aarch64-none-elf/bin/ld: reios_elf.cpp:(.text._Z13reios_loadElfRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x104): undefined reference to `elf_getNumProgramHeaders'
/opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/13.1.0/../../../../aarch64-none-elf/bin/ld: reios_elf.cpp:(.text._Z13reios_loadElfRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x11c): undefined reference to `elf_getProgramHeaderVaddr'
/opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/13.1.0/../../../../aarch64-none-elf/bin/ld: reios_elf.cpp:(.text._Z13reios_loadElfRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x12c): undefined reference to `elf_getProgramHeaderFileSize'
/opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/13.1.0/../../../../aarch64-none-elf/bin/ld: reios_elf.cpp:(.text._Z13reios_loadElfRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x140): undefined reference to `elf_getProgramHeaderOffset'
/opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/13.1.0/../../../../aarch64-none-elf/bin/ld: reios_elf.cpp:(.text._Z13reios_loadElfRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x174): undefined reference to `elf_getProgramHeaderMemorySize'
/opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/13.1.0/../../../../aarch64-none-elf/bin/ld: /opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/13.1.0/../../../../aarch64-none-elf/bin/ld: DWARF error: can't find .debug_ranges section.
libretro_libnx.a(nvmem.o): in function `nvmem::loadFlashResource(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long&)':
nvmem.cpp:(.text._ZN5nvmemL17loadFlashResourceERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERm+0x20): undefined reference to `cmrc::flycast::get_filesystem()'
collect2: error: ld returned 1 exit status
make: *** [/opt/devkitpro/libnx/switch_rules:81: retroarch_switch.elf] Error 1
```

Steps to reproduce:
* Flycast built using CMake commands used in GitHub workflows:
  * `$DEVKITPRO/portlibs/switch/bin/aarch64-none-elf-cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=artifact -G Ninja -DLIBRETRO=ON` (CMakeLists.txt slightly modified to replace expected `*.obj` files with the generated `*.o` files in last build step)
  * `cmake --build build --config Release --target install`
* Resulting `flycast_libretro_libnx.a` artifact copied to retroarch directory as `libretro_libnx.a`
* RetroArch built with `make -f Makefile.libnx`

**Comment by flyinghead** [comment] 2023-06-04 14:40
Unfortunately the retroarch switch build isn't being maintained so it's not surprising that it's failing.
I believe you need an additional step to include all object files from dependent libraries (`libelf.a`, `libflycast-resources.a`) into the `libretro_libnx.a` library.

**Comment by flyinghead** [comment] 2023-06-04 14:42
oh actually it's done in CMakeLists.txt:
```
add_custom_target(combined ALL
	COMMAND ${CMAKE_AR} -x $<TARGET_FILE:xxHash::xxhash>
	COMMAND ${CMAKE_AR} -x $<TARGET_FILE:chdr-static>
	COMMAND ${CMAKE_AR} -x $<TARGET_FILE:zip>
	COMMAND ${CMAKE_AR} -rs flycast_libretro_libnx.a *.obj
	COMMAND rm *.obj
```

Adding the two previously mentioned libraries to the list should fix the issue.

**Comment by flyinghead** [comment] 2023-06-04 14:53
as in:
```
add_custom_target(combined ALL
	COMMAND ${CMAKE_AR} -x $<TARGET_FILE:xxHash::xxhash>
	COMMAND ${CMAKE_AR} -x $<TARGET_FILE:chdr-static>
	COMMAND ${CMAKE_AR} -x $<TARGET_FILE:zip>
	COMMAND ${CMAKE_AR} -x $<TARGET_FILE:elf>
	COMMAND ${CMAKE_AR} -x $<TARGET_FILE:flycast::res>
	COMMAND ${CMAKE_AR} -rs flycast_libretro_libnx.a *.obj
```

**Comment by aitorciki** [comment] 2023-06-04 15:20
Hey, thanks for the guidance (I'm a total newby to CMake).

I added the dependencies as proposed (renaming *.obj to *.o, probably caused by my using a newer devkitpro version?):
```
add_custom_target(combined ALL
        COMMAND ${CMAKE_AR} -x $<TARGET_FILE:xxHash::xxhash>
        COMMAND ${CMAKE_AR} -x $<TARGET_FILE:chdr-static>
        COMMAND ${CMAKE_AR} -x $<TARGET_FILE:zip>
        COMMAND ${CMAKE_AR} -x $<TARGET_FILE:elf>
        COMMAND ${CMAKE_AR} -x $<TARGET_FILE:flycast-resources>
        COMMAND ${CMAKE_AR} -rs flycast_libretro_libnx.a *.o
        COMMAND rm *.o
        WORKING_DIRECTORY ${CMAKE_BINARY_DIR}/${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}
        DEPENDS xxHash::xxhash chdr-static zip elf flycast-resources ${PROJECT_NAME})
```

The up-to-date core now builds and runs nicely!

Probably worth updating for folks who want an up-to-date Switch core, happy to make a PR if needed (still curious by the *.obj vs *.o situation though).

**Comment by flyinghead** [comment] 2023-06-04 15:40
I'll fix `CMakeLists.txt` now that you've confirmed that it's building fine.

The *.obj vs. *.o issue is due to a change in the devkitpro environment. Flycast is being built with an old devkitpro version because new ones have performance issues. Unfortunately I can't test since I don't have a switch so I have to rely on user reports.

**Comment by flyinghead** [comment] 2023-06-07 08:44
fixed by the commit above

**Closed by flyinghead** 2023-06-07 08:44 UTC
Labels: bug
