### ISSUE TITLE
[Libretro] Can't build current version (small translation problem apparently)

### ISSUE THREAD

**Issue by vanfanel** [flyinghead/flycast#1718] opened 2024-10-29 13:40 UTC
Platform / OS / Hardware: Linux

Flycast version: current GIT

Hardware: x86_64

**_Description of the Issue_**

Building current GIT code is impossible because of these errors:

```
In file included from /root/src/libretro/flycast/shell/libretro/libretro_core_options.h:29,
                 from /root/src/libretro/flycast/shell/libretro/libretro.cpp:103:
/root/src/libretro/flycast/shell/libretro/libretro_core_options_intl.h:46623:53: warning: unknown escape sequence: '\L'
46623 | #define CORE_OPTION_NAME_PER_CONTENT_VMUS_INFO_0_IT "Se disabilitato, tutti i giochi condividono fino a 8 file VMU di salvataggio (A1/A2/B1/B2/C1/C2/D1/D2) situati nella cartella di sistema di RetroArch.\n\L'impostazione 'VMU A1' crea un file VMU 'A1' unico nella cartella di salvataggio di RetroArch, per ogni gioco che viene lanciato.\n\L'impostazione 'All VMUs' crea fino a 8 file VMU unici (A1/A2/B1/B2/C1/C2/D1/D2) per ogni gioco che viene lanciato."
      |                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/src/libretro/flycast/shell/libretro/libretro_core_options_intl.h:47721:7: note: in expansion of macro ‘CORE_OPTION_NAME_PER_CONTENT_VMUS_INFO_0_IT’
47721 |       CORE_OPTION_NAME_PER_CONTENT_VMUS_INFO_0_IT,
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/src/libretro/flycast/shell/libretro/libretro_core_options_intl.h:46623:53: warning: unknown escape sequence: '\L'
46623 | #define CORE_OPTION_NAME_PER_CONTENT_VMUS_INFO_0_IT "Se disabilitato, tutti i giochi condividono fino a 8 file VMU di salvataggio (A1/A2/B1/B2/C1/C2/D1/D2) situati nella cartella di sistema di RetroArch.\n\L'impostazione 'VMU A1' crea un file VMU 'A1' unico nella cartella di salvataggio di RetroArch, per ogni gioco che viene lanciato.\n\L'impostazione 'All VMUs' crea fino a 8 file VMU unici (A1/A2/B1/B2/C1/C2/D1/D2) per ogni gioco che viene lanciato."
      |                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/src/libretro/flycast/shell/libretro/libretro_core_options_intl.h:47721:7: note: in expansion of macro ‘CORE_OPTION_NAME_PER_CONTENT_VMUS_INFO_0_IT’
47721 |       CORE_OPTION_NAME_PER_CONTENT_VMUS_INFO_0_IT,
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/src/libretro/flycast/shell/libretro/libretro_core_options_intl.h:50649:53: warning: unknown escape sequence: '\040'
50649 | #define CORE_OPTION_NAME_PER_CONTENT_VMUS_INFO_0_KO "<U+BE44><U+D65C><U+C131><U+D654><U+D560> <U+ACBD><U+C6B0>, <U+BAA8><U+B4E0> <U+AC8C><U+C784><U+C774> RetroArch<U+C758> <U+C2DC><U+C2A4><U+D15C> <U+D3F4><U+B354><U+C5D0> <U+C800><U+C7A5><U+B41C> <U+CD5C><U+B300> 8<U+AC1C><U+C758> VMU <U+C800><U+C7A5> <U+D30C><U+C77C>(A1/A2/B1/B2/C1/C2/D1/D2)<U+C744> <U+ACF5><U+C720><U+D569><U+B2C8><U+B2E4>.\n\ 'VMU A1' <U+C635><U+C158><U+C740> RetroArch<U+C758> <U+C800><U+C7A5> <U+D3F4><U+B354><U+C5D0> <U+AC8C><U+C784> <U+D558><U+B098> <U+B2F9> <U+D558><U+B098><U+C758> VMU 'A1' <U+D30C><U+C77C><U+C744> <U+C0DD><U+C131><U+D569><U+B2C8><U+B2E4>.\n\ '<U+BAA8><U+B4E0> VMU'<U+B294> <U+AC8C><U+C784> <U+D558><U+B098> <U+B2F9> <U+CD5C><U+B300> 8<U+AC1C><U+C758> VMU <U+D30C><U+C77C>(A1/A2/B1/B2/C1/C2/D1/D2)<U+C744> <U+C0DD><U+C131><U+D569><U+B2C8><U+B2E4>."
      |                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/src/libretro/flycast/shell/libretro/libretro_core_options_intl.h:51747:7: note: in expansion of macro ‘CORE_OPTION_NAME_PER_CONTENT_VMUS_INFO_0_KO’
51747 |       CORE_OPTION_NAME_PER_CONTENT_VMUS_INFO_0_KO,
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/src/libretro/flycast/shell/libretro/libretro_core_options_intl.h:50649:53: warning: unknown escape sequence: '\040'
50649 | #define CORE_OPTION_NAME_PER_CONTENT_VMUS_INFO_0_KO "<U+BE44><U+D65C><U+C131><U+D654><U+D560> <U+ACBD><U+C6B0>, <U+BAA8><U+B4E0> <U+AC8C><U+C784><U+C774> RetroArch<U+C758> <U+C2DC><U+C2A4><U+D15C> <U+D3F4><U+B354><U+C5D0> <U+C800><U+C7A5><U+B41C> <U+CD5C><U+B300> 8<U+AC1C><U+C758> VMU <U+C800><U+C7A5> <U+D30C><U+C77C>(A1/A2/B1/B2/C1/C2/D1/D2)<U+C744> <U+ACF5><U+C720><U+D569><U+B2C8><U+B2E4>.\n\ 'VMU A1' <U+C635><U+C158><U+C740> RetroArch<U+C758> <U+C800><U+C7A5> <U+D3F4><U+B354><U+C5D0> <U+AC8C><U+C784> <U+D558><U+B098> <U+B2F9> <U+D558><U+B098><U+C758> VMU 'A1' <U+D30C><U+C77C><U+C744> <U+C0DD><U+C131><U+D569><U+B2C8><U+B2E4>.\n\ '<U+BAA8><U+B4E0> VMU'<U+B294> <U+AC8C><U+C784> <U+D558><U+B098> <U+B2F9> <U+CD5C><U+B300> 8<U+AC1C><U+C758> VMU <U+D30C><U+C77C>(A1/A2/B1/B2/C1/C2/D1/D2)<U+C744> <U+C0DD><U+C131><U+D569><U+B2C8><U+B2E4>."
      |                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/src/libretro/flycast/shell/libretro/libretro_core_options_intl.h:51747:7: note: in expansion of macro ‘CORE_OPTION_NAME_PER_CONTENT_VMUS_INFO_0_KO’
51747 |       CORE_OPTION_NAME_PER_CONTENT_VMUS_INFO_0_KO,
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/src/libretro/flycast/shell/libretro/libretro_core_options_intl.h:58701:53: error: incomplete universal character name \U
58701 | #define CORE_OPTION_NAME_PER_CONTENT_VMUS_INFO_0_PL "Gdy wyłączone, wszystkie gry udostępniają do 8 plików zapisów VMU (A1/A2/B1/B2/C1/C2/D1/D2) znajdujących się w folderze systemowym RetroArch.\n\Ustawienie 'VMU A1' tworzy unikalny plik VMU 'A1' w folderze zapisów RetroArcha dla każdej uruchomionej gry.\n\Ustawienie 'Wszystkie VMU' tworzy do 8 unikalnych plików VMU (A1/A2/B1/B2/C1/C2/D1/D2/D2) dla każdej uruchomionej gry."
      |                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/src/libretro/flycast/shell/libretro/libretro_core_options_intl.h:59799:7: note: in expansion of macro ‘CORE_OPTION_NAME_PER_CONTENT_VMUS_INFO_0_PL’
59799 |       CORE_OPTION_NAME_PER_CONTENT_VMUS_INFO_0_PL,
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/src/libretro/flycast/shell/libretro/libretro_core_options_intl.h:58701:53: error: incomplete universal character name \U
58701 | #define CORE_OPTION_NAME_PER_CONTENT_VMUS_INFO_0_PL "Gdy wyłączone, wszystkie gry udostępniają do 8 plików zapisów VMU (A1/A2/B1/B2/C1/C2/D1/D2) znajdujących się w folderze systemowym RetroArch.\n\Ustawienie 'VMU A1' tworzy unikalny plik VMU 'A1' w folderze zapisów RetroArcha dla każdej uruchomionej gry.\n\Ustawienie 'Wszystkie VMU' tworzy do 8 unikalnych plików VMU (A1/A2/B1/B2/C1/C2/D1/D2/D2) dla każdej uruchomionej gry."
      |                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/src/libretro/flycast/shell/libretro/libretro_core_options_intl.h:59799:7: note: in expansion of macro ‘CORE_OPTION_NAME_PER_CONTENT_VMUS_INFO_0_PL’
59799 |       CORE_OPTION_NAME_PER_CONTENT_VMUS_INFO_0_PL,
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by flyinghead** [comment] 2024-10-29 13:44
duplicate of #1688

**Closed as not planned by flyinghead** 2024-10-29 13:44 UTC
Labels: bug

**Comment by vanfanel** [comment] 2024-10-29 13:45
Oops, sorry
