### ISSUE TITLE
DreamEye™ support

### ISSUE THREAD

**Issue by dobkun** [flyinghead/flycast#1469] opened 2024-03-26 09:02 UTC
Dreameye (ドリームアイ) was a digital camera released for the Dreamcast home video console by Sega. It was designed to be used as a webcam and a digital still camera, and there were plans for games to involve the Dreameye. The Dreameye was only released in Japan. It came with the Divers 2000 Dreamcast and was also sold separately.
The Dreameye came with a microphone headset, a stand, batteries, software, a cable to connect the Dreameye to the Dreamcast and a Dreameye microphone plug card. The Dreameye took pictures at (for the time) an astounding 3 megapixels, but in order to send them via e-mail the pictures in question had to be first saved to a VMU. Upon transferring the pictures off the card they resized to a resolution of 320px by 240px.
you should implement this feature, despite the fact that the only "game" supported is VisualPark.
it will use any connected camera(and a microphone).

**Comment by dobkun** [comment] 2024-03-26 09:03
also an ability to manage multiple VMU memory images.

**Comment by flyinghead** [comment] 2024-03-26 09:18
duplicate of #935

**Closed by flyinghead** 2024-03-26 09:18 UTC
Labels: enhancement
