### ISSUE TITLE
Disc swapping is not working properly in Skies of Arcadia

### ISSUE THREAD

**Issue by bslenul** [flyinghead/flycast#189] opened 2021-02-26 13:25 UTC
Platform / OS / Hardware: PC, Windows 10 64bit

Github hash: bbcfc8354a5281b612553b3d4e2051e69c3d15b2

Hardware: i5-4670K, GTX 970

**_Description of the Issue_**

Disc swapping seems to be broken with Skies of Arcadia (bbcfc8354a5281b612553b3d4e2051e69c3d15b2 being the current commit when typing this), sometimes after inserting the new disc it just freezes on the "Checking disc data..." screen, sometimes it sends you to BIOS directly after this screen and sometimes (but it's pretty rare) it boots just fine. It seems to consistently boot fine with interpreter or HLE BIOS.

**_Debugging Steps Tested_**

* Boot Skies of Arcadia disc 2.
* Start a new game.
* Eject disc when asked.
* Insert disc 1.
* It will say "Checking disc data..." then either it will be stuck or it will send you to BIOS. If you're lucky it will boot just fine.

**Comment by flyinghead** [comment] 2021-02-27 09:10
I'm not sure there is any regression here. Games use different methods for switching disk.

Shenmue exits to BIOS as soon as the disk tray is open. This can be seen here: https://youtu.be/bpIu5iNnbDo?t=17060.

Skies of Arcadia disk switching sometimes work, sometimes doesn't (hanging on "Checking disk data" or rebooting to BIOS). This can probably be improved.

The most critical one is D2 because proper disk switching is required in order to continue the game. Other multidisk games are fine if saving to VMU and restarting the game with the next disk. (Correct me if I'm wrong here.)

**Comment by bslenul** [comment] 2021-02-27 10:28
> Shenmue exits to BIOS as soon as the disk tray is open. This can be seen here: https://youtu.be/bpIu5iNnbDo?t=17060.

Oooh so it happens even on real hardware, I didn't remember that, my bad!

But yeah Skies of Arcadia made me super confused, I thought I bisected properly with the libretro core, then when I tried it again few hours later it didn't work anymore... I made more tests earlier today and yeah, noticed it was random, I was about to post a video showing its weird behavior but you're already aware of it.

At first I thought it was a regression since I didn't see any issue opened about it but it probably isn't, should I still keep this open? With an edit to make it a Skies of Arcadia issue only?

D2 swap is currently broken on the libretro core however, I'll see if the changes made in 3bc508deea6e624dc110a84558f8f49b1990f2c7 can work on it.

Anyway, thanks for replying and for the clarifications! Sorry again for the false alarm about Shenmue :x

**Comment by flyinghead** [comment] 2021-02-27 11:01
The commit you mention will certainly fix the D2 problem on the core.

After some more testing with SoA, disk switching doesn't seem to work at all with a real BIOS and works randomly with HLE BIOS.

**Comment by bslenul** [comment] 2021-02-27 11:21
I got it to boot a few times with real BIOS but it's pretty rare, with HLE I just tried like ~10 times in a raw, got it to boot 9 times, 1 time the "Checking disc data..." disapearred but the game was stuck.

**Comment by flyinghead** [comment] 2024-01-24 18:53
This should be fixed in the latest `dev` build.

**Comment by bslenul** [comment] 2024-01-24 19:46
Just tested with Skies of Arcadia (booting from disc 2 then either selecting "new game" or loading a disc 1 save) and the game is stuck on the "please insert disc 1 and close the disc door" screen after swapping discs. Same behavior on both standalone and the Libretro core (both 10d3ffdf09483d0b65311dbc5b405266f219f57e).

The swap still works fine when using the HLE BIOS.

**Comment by flyinghead** [comment] 2024-01-24 20:22
Right, a last minute change broke this game. More work needed.

**Comment by flyinghead** [comment] 2024-01-24 20:27
And thank you for your lightspeed fast report. I could pinpoint the issue in no time while it's still hot.

**Comment by flyinghead** [comment] 2024-01-25 11:46
It should now be fixed by https://github.com/flyinghead/flycast/commit/116dc0e1ed9313a4cba19d63cf68b4a12bcd5237

**Comment by bslenul** [comment] 2024-01-25 13:39
Skies of Arcadia works great now 👍 However it doesn't seem to work with Resident Evil Code Veronica and Alone in the Dark, both games are telling me I inserted the incorrect disc.

D2 still swaps fine. I can't remember if Shenmue II was working previously, but it works.

Should I close this so we can continue in #1046? Instead of having 2 similar issues :p

**Closed** 2024-01-25 15:33 UTC
Labels: bug
