### ISSUE TITLE
Google Play build frontend support regression 

### ISSUE THREAD

**Issue by Jetup13** [flyinghead/flycast#1597] opened 2024-08-09 00:42 UTC
Android builds tried:

(master) 45bf218,  (dev) 2a4356e, & (Google Play) v2.3.2-164-g33d1dafdb

Device:

Samsung 10e (A12)

It seems that the Google Play build no long supports frontend launching. Instead of opening the game it goes to the main menu of Flycast. GitHub master & dev builds still work with the following am start argument:

> -n com.flycast.emulator/com.flycast.emulator.MainActivity
> -a android.intent.action.VIEW
> -d {file.path}

I've tried the above argument and one with {file.uri} as I thought the Google Play might require uri paths to be passed. 

I assume the issue stems from Google Play restrictions?

**Comment by flyinghead** [comment] 2024-08-15 10:03
Duplicate of #1584

**Closed by flyinghead** 2024-08-15 10:03 UTC
Labels: bug
