### ISSUE TITLE
[Feature Request] RetroAchievements support

### ISSUE THREAD

**Issue by Tvastr-ops** [flyinghead/flycast#761] opened 2022-10-01 11:08 UTC
**Is your feature request related to a problem? Please describe.**
Currently the only way to get RetroAchievements to work with flycast is through Retroarch core. But it's a very tedious process. And installing Retroarch for only Dreamcast doesn't make sense. So if it's possible can you please add RA support in the standalone application.

**Comment by ludg1e** [comment] 2022-10-09 12:59
Why only Android/iOS? This should address to all platforms, if possible.

**Comment by TreeBranches** [comment] 2022-11-26 07:23
Considering the native Xbox port of Flycast runs significantly better than the Retroarch core I too would like to see this happen now now that achievements are supported in Dreamcast games.

**Comment by DLance96** [comment] 2022-11-28 03:57
Just wanted to share my desire to see this feature

**Comment by Darkorigins7323** [comment] 2023-03-01 17:49
I agree with everyone! I would love too see this happen. But sadly I’m not a dev and I don’t know much about emulator development/ emulation.

**Comment by retropieuser** [comment] 2023-07-11 11:03
Apologies I didn't see this ticket. I'd also love to see this implemented

**Comment by Walissonsd** [comment] 2023-08-21 00:09
Please add Retroachievements

**Comment by montero3006** [comment] 2023-10-10 21:46
Hello, thanks for that awesome emulator. Will be possibility to have retroachivements support on the emulator? Thanks!

**Comment by w-e-g** [comment] 2023-11-12 11:31
+1, it would be very nice if add a retroachivments support.

**Comment by jintei** [comment] 2024-04-24 20:23
Flycast is so much better standalone than emulated via RetroArch, really wish we could have RA support for it

**Comment by flyinghead** [comment] 2024-04-29 13:59
The latest build on the `dev` branch features a basic RetroAchievements integration. UI is very minimal at this point and you'll just get text notifications when achievements are unlocked. However everything should be tracked on the retroachievements.org web site.
This is supported on all platforms.
Please test and comment with your feedback. Don't forget to enable Automatic Crash Reporting.

**Comment by w-e-g** [comment] 2024-04-29 16:41
Just downloaded the freshest dev build. It crashes when I tried to began input text to login/password field.

**Comment by flyinghead** [comment] 2024-04-29 16:44
@w-e-g which platforms are you on?

**Comment by w-e-g** [comment] 2024-04-29 16:48
macOS Sonoma 14.4.1, x86_64.

**Comment by nexus382** [comment] 2024-04-29 17:21
android seems ok, no issues yet, logged in and what not,

**Comment by flyinghead** [comment] 2024-04-29 17:28
@w-e-g Can you try the previous dev build?
There are UI text fields in the Settings > Network tab. Please test entering text and check if it crashes with this version.
Thanks.

**Comment by bryanforbes** [comment] 2024-04-29 17:38
> Well, you're lucky because it doesn't even start on my machine. It looks like the macOS build is broken.

I just tried the 4666ea2 build on macOS Sonoma 14.3. It runs, logs in, and I got my first achievement.

**Comment by w-e-g** [comment] 2024-04-29 17:58
@flyinghead, I just tested 4666ea2. Same situation. Build 8fdd1dd for macOS was not built if I understand corretly.

**Comment by flyinghead** [comment] 2024-04-29 18:09
https://github.com/flyinghead/flycast/commit/4666ea2fdba1a0c225dc99b7cb693962ad494749 is the latest build.
Could you test the previous build for macOS: [e46815d](https://github.com/flyinghead/flycast/commit/e46815d)

It doesn't have RetroAchievements support but I need to find out in which build the problem started.

**Comment by w-e-g** [comment] 2024-04-29 18:56
@flyinghead test build  e46815d. Enter the text into "Network" tab. Works fine.

**Comment by retropieuser** [comment] 2024-04-29 21:31
Mac M1 Sonoma 14.2.1, using the latest build loads fine with the username and password entered

**Comment by vkedwardli** [comment] 2024-05-01 12:08
@w-e-g Do you mean with the build https://github.com/flyinghead/flycast/commit/4666ea2fdba1a0c225dc99b7cb693962ad494749, it also crashes when you try to type text in the Network tab? Or does it just crash in the `Enable RetroAchievements`'s `Username` field?

Are you using any Input Method Editor or just standard English input?

**Comment by w-e-g** [comment] 2024-05-01 15:46
@vkedwardli it crashes when using any text field. In network tab or retroachievements. I'm using English locale and input English text only into the text fields. No any non-standard texpt input used.

**Comment by flyinghead** [comment] 2024-05-01 16:55
New `dev` build with better UI is available
![image](https://github.com/flyinghead/flycast/assets/16261910/ff3a7c69-9eb5-4402-b2cd-60f4b9438feb)

@w-e-g vkedwardli also provided a patch for macOS. Please test and let us know.

**Comment by w-e-g** [comment] 2024-05-01 17:10
@flyinghead Very nice! It works and I unlocked achievement! :) 🔥

**Comment by flyinghead** [comment] 2024-05-01 17:16
Party time!

**Comment by flyinghead** [comment] 2024-05-03 18:50
New dev build available:
![image](https://github.com/flyinghead/flycast/assets/16261910/18fc3c36-cdb6-46fc-8315-34e0c182318b)

![image](https://github.com/flyinghead/flycast/assets/16261910/5002e755-f474-4eef-8883-8d2131df3f43)

**Comment by retropieuser** [comment] 2024-05-04 10:49
Still all good for me, tested on Mac M1 Sonoma 14.2.1, using fe17d45. Do you have a roadmap of functions you're looking to implement to have it fully working? I can see you've got a placeholder for hardcore mode inside the emu.cfg for example?

**Comment by flyinghead** [comment] 2024-05-04 14:15
I just fixed a crash on windows that was reported automatically so this is good.
Hardcore mode is next, then there are leaderboards than need specific indicators. After that we should be close to complete.
@TheCoolPup reported that achievements weren't working on arcade games. (He was testing house of the dead 2.) So any help in this area would be appreciated.

**Comment by retropieuser** [comment] 2024-05-04 15:29
Re Naomi games, I just tried Monkey ball and HOTD2 on my setup with the above build and it unlocks okay for me

**Comment by flyinghead** [comment] 2024-05-04 15:40
Great! Thanks for testing and reporting.

**Comment by flyinghead** [comment] 2024-05-05 14:27
Hardcore mode is available in the latest dev build.
Note that it must be enabled before starting a game to take effect. However, it can be disabled once a game is started.

**Comment by Blackbird88** [comment] 2024-05-05 15:30
Minor nitpick. Instead of showing "0 of 0 achievements"  for games without achievements, it would be better to show "This game has no achievements" like PCSX2

flycast
![image](https://github.com/flyinghead/flycast/assets/4414625/f56a5ccf-8b05-4a55-acfe-cfcc6c12e785)
PCSX2
![image](https://github.com/flyinghead/flycast/assets/4414625/c40637e6-1779-4a5b-ab3f-a84932238650)

**Comment by retropieuser** [comment] 2024-05-05 17:45
> Hardcore mode is available in the latest dev build. Note that it must be enabled before starting a game to take effect. However, it can be disabled once a game is started.

Epic, those are working for me. I also tested unlocking an achievement I had already in softcore mode and it worked fine giving me the hardcore cheevo

**Comment by flyinghead** [comment] 2024-05-07 16:08
Yet another dev build available, this time with leaderboard notifications and trackers. 
I think we're feature complete at this point.
Let me know of any issue you find and if anything is missing.

**Comment by Blackbird88** [comment] 2024-05-07 16:30
The latest dev branch commit [f76d05a](https://github.com/flyinghead/flycast/commit/f76d05a) doesn't launch for me on W11 x64. [7327e52](https://github.com/flyinghead/flycast/commit/7327e52) is last one that works.

**Comment by flyinghead** [comment] 2024-05-07 16:41
Anything in the log?

**Comment by Blackbird88** [comment] 2024-05-07 16:44
I don't see any log file anywhere, either it crashes too soon or I can't find it.

**Comment by flyinghead** [comment] 2024-05-07 16:45
I haven't received any crash report (yet?)

**Comment by flyinghead** [comment] 2024-05-07 16:46
if you enable "Log to File" it should create a `flycast.log` in the flycast directory

**Comment by flyinghead** [comment] 2024-05-07 16:48
Yes the last build is crashing fro me too, very early.

**Comment by Blackbird88** [comment] 2024-05-07 16:50
I enabled that and no log is being created. RIP

**Comment by Blackbird88** [comment] 2024-05-08 11:28
Works for me!
This reminds I forgot to report one thing. When using pad to navigate the UI it's impossible to scroll the achievements here. One has to click into the area first. Annoying on platforms that are gamepad only.
![image](https://github.com/flyinghead/flycast/assets/4414625/a83cd11e-7e6a-424d-85c0-5f3dcc6400e0)

Unsure if it's some imgui limitation?

**Comment by kihato** [comment] 2024-05-09 12:44
For certain games, thumbnails may be displayed by mistake.

![Veronica](https://github.com/flyinghead/flycast/assets/14366233/caec6c6d-68fc-4c5e-bc42-0d2ccaeadee2)
![DolphinBlue](https://github.com/flyinghead/flycast/assets/14366233/aec30bd8-1da0-4650-9a2a-370aa3093be8)
![KOF XI](https://github.com/flyinghead/flycast/assets/14366233/98fd4955-9af1-4a66-8a83-b8d8769273b6)

**Comment by flyinghead** [comment] 2024-05-09 13:18
These icons are the "Active Challenges" so it's normal to see them until you unlock or loose them. You can see the list in the Achievements screen:
![image](https://github.com/flyinghead/flycast/assets/16261910/479f48db-d2bb-4acb-b5b3-b16cf466d2da)

However the dimensions of the Dolphin Blue and KOF XI active challenges pop ups are clearly incorrect.

**Comment by kihato** [comment] 2024-05-10 17:44
Thanks for correcting the display!
When I retrieve leaderboard information, the Active Challenges icons disappears. Is this by design?

![MetalSlug6](https://github.com/flyinghead/flycast/assets/14366233/50e81469-4d01-4ea6-89c1-4b0ec21f694b)

**Comment by flyinghead** [comment] 2024-05-10 17:56
The display of indicators/messages is handled by RetroAchievement for the most part. So it won't display both active challenge indicators and leaderboard trackers.

**Comment by flyinghead** [comment] 2024-05-21 05:23
RetroAchievements explicitly forbids widescreen cheats in hardcore mode:
“ When in hardcore mode, you must limit any emulator features that could be seen as providing an advantage to the user. Common features that are hardcore-restricted are:
Loading save states (saving save states is okay)
Cheats that modify gameplay (i.e. GameGenie codes or widescreen enhancements) (upscaling is okay)”
https://github.com/RetroAchievements/rcheevos/wiki/rc_client-integration#enabling-hardcore

**Comment by Blackbird88** [comment] 2024-05-23 15:04
So I finally got time to test this and it works great, however I just realized that there's no notification sounds. Will they be added eventually?

**Comment by boldcesar** [comment] 2024-05-23 19:17
Hello, i'm trying this new feature (thanks for that in advance).
I tested Tony Hawks 1 and everytime a achievements pops-up the game freezes about a second then goes back to normal.
I set the emulator to Vulkan and Per Game VMU to on, everything else are in default settings. And i'm using the latest Appimage.

**Comment by flyinghead** [comment] 2024-05-23 19:56
Have you tested other games?

**Comment by TheCoolPup** [comment] 2024-05-23 20:38
Can confirm this happens in other games

**Comment by flyinghead** [comment] 2024-05-23 20:42
Which ones?

**Comment by TheCoolPup** [comment] 2024-05-23 20:43
I’ve noticed this happens in most games, for example, i noticed this in crazy taxi, and street fighter 3 double impact

**Comment by TheCoolPup** [comment] 2024-05-23 20:46
What’s strange in a emulator like pcsx2, it doesn’t freeze at all when a achievement happens

**Comment by boldcesar** [comment] 2024-05-23 20:47
> Have you tested other games?

Now i tested, on Capcom vs SNK 1 and Crazy Taxi 1, when the cheevo pops up a micro stuttering happens. On Tony Hawk is a heavy stutter, it freezes, in the other two games i've mentioned only a micro stuttering happens..

**Comment by TheCoolPup** [comment] 2024-05-23 20:48
I’m curious if it happens if Flycast is like communicating with the ra site???

**Comment by flyinghead** [comment] 2024-05-23 20:52
Just tested Crazy Taxi and I got a micro freeze on one achievement out of 4. But nothing remotely close to 1 second.

**Comment by boldcesar** [comment] 2024-05-23 21:18
> Just tested Crazy Taxi and I got a micro freeze on one achievement out of 4. But nothing remotely close to 1 second.

Yes, the heavy stutter occurred on Tony Hawk's, the other games occurred only a micro stutter . I will play other games and let you if this happens too.

**Comment by flyinghead** [comment] 2024-05-24 08:32
i found the reason for these micro freezes: the image is downloaded in the same thread as the emulator. I'm working on a fix.
Now this could potentially cause long freezes in case of network slowdown or interruption. But that doesn't explain why a particular game would hang and not others. In particular, the images are cached so unlocking an achievement again (after resetting it) should not cause any freeze.

Unfortunately I don't know how to play Tony Hawk. Is there a way you could upload a savestate in which I could unlock an achievement easily? That would help me figure out the issue with this game if any.

**Comment by boldcesar** [comment] 2024-05-24 14:31
I think i had it something wrong on my system, i swapped to Opensuse and it's occurring only a micro freeze too in Tony Hawk.
And i tested what you said, playing after the thumbnails are already cached doesn't result on a micro freeze. Perharps you could put the emulator to pre-download all images on the first game boot? I think RetroArch do something like that? But i could be talking non sense since i don't understand this level of coding. I'm just trying to help improve.

**Comment by flyinghead** [comment] 2024-05-24 16:28
The freeze should be fixed in the latest `master` build.

**Comment by Relwi** [comment] 2024-05-25 10:09
Hey, first of all, thanks for this implementation!
I logged to RetroAchievements successfully and I'm playing in hardcore mode, the thing is that I can spam the pause button on this mode and I think that shouldn't be possible https://github.com/RetroAchievements/rcheevos/wiki/rc_client-integration#preventing-pause-spam

**Comment by flyinghead** [comment] 2024-05-27 08:27
Pausing is now restricted in hardcore mode (latest `master` build)

**Comment by JomSpoons** [comment] 2024-09-10 23:41
First off I'd like to say I greatly appreciate support for RetroAchievements through Flycast, as I much prefer standalone emulators to something like a libretro core. I requested that Flycast get added to RA's "[Download a supported emulator](https://retroachievements.org/download.php)" through the RA Discord server. I was told that the devs of the emulator have to get into contact with the RA staff in order to have the emulator listed as officially supported, so I suggest that you do so. Thank you!

**Comment by TheFearlessDeath500** [comment] 2024-09-29 13:23
I agree with @JomSpoons on this one. Just contacting the RA devs seems like something really simple imo.

**Comment by handyTheLoser** [comment] 2024-10-31 20:30
I've noticed that some games like Tony Hawk's Pro Skater 2 has achievements but It's greyed out in the emulator. How can I fix this?

**Comment by handyTheLoser** [comment] 2024-10-31 22:47
Oh, I see. Thanks.

**Closed** 2024-11-02 10:10 UTC
Labels: enhancement
