### ISSUE TITLE
Sonic adventure 1: sonics face graphical glitch 

### ISSUE THREAD

**Issue by D2firegit** [flyinghead/flycast#1443] opened 2024-03-06 23:41 UTC
Platform / OS / Hardware: Dreamcast: flycast standalone v2.2-206-g0aa891074 / Android 13/ Motorola edge 2022 / arm mali g610 mc3 gpu . MediaTek Dimensity 1050 (6 nm) Octa-core CPU (2x2.5 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55). 8gb ram. 

Github hash: 0aa8910

Sonic face graphical glitch

**_Debugging Steps Tested_**

  * Tried per pixel using vulkan instead of open gl 3.2, but fps is significantly reduced. 

**_Logs Gathered_**
00:29:280 audio/audiobackend_oboe.cpp:121 N[AUDIO]: Oboe driver started. stream capacity: 1418 frames, size: 1418 frames, frames/callback: 512, frames/burst: 472
00:30:744 audio/audiobackend_oboe.cpp:128 N[AUDIO]: Oboe driver stopping
00:00:873 wsi/egl.cpp:47 N[RENDERER]: EGL version 1.4
00:00:914 wsi/egl.cpp:156 N[RENDERER]: eglQuerySurface: 2175 - 1020
00:00:920 rend/gui.cpp:303 N[RENDERER]: Screen DPI is 402, size 2175 x 1020. Scaling by 3.01
00:00:920 rend/gles/gles.cpp:637 N[RENDERER]: OpenGL ES version 3.2
00:00:920 rend/gles/gles.cpp:638 N[RENDERER]: Vendor 'ARM' Renderer 'Mali-G610 MC3' Version 'OpenGL ES 3.2 v1.r32p1-01eac0.a031c769622e85782e9b68c066a81213'
00:01:133 wsi/egl.cpp:47 N[RENDERER]: EGL version 1.4
00:01:148 wsi/egl.cpp:156 N[RENDERER]: eglQuerySurface: 2400 - 1080
00:01:148 rend/gles/gles.cpp:637 N[RENDERER]: OpenGL ES version 3.2
00:01:148 rend/gles/gles.cpp:638 N[RENDERER]: Vendor 'ARM' Renderer 'Mali-G610 MC3' Version 'OpenGL ES 3.2 v1.r32p1-01eac0.a031c769622e85782e9b68c066a81213'
00:02:307 hw/mem/addrspace.cpp:431 N[VMEM]: Info: nvmem is enabled
00:02:318 hw/mem/addrspace.cpp:467 N[VMEM]: BASE 0x775f7f0000 RAM(16 MB) 0x776b7f0000 VRAM64(8 MB) 0x77637f0000 ARAM(2 MB) 0x777f7f0000
00:02:333 hw/mem/addrspace.cpp:431 N[VMEM]: Info: nvmem is enabled
00:02:342 hw/mem/addrspace.cpp:467 N[VMEM]: BASE 0x775f7f0000 RAM(16 MB) 0x776b7f0000 VRAM64(8 MB) 0x77637f0000 ARAM(2 MB) 0x777f7f0000
00:02:351 emulator.cpp:54 N[BOOT]: Game ID is [MK-51000]
00:02:357 emulator.cpp:487 N[BOOT]: Did not load BIOS, using reios
00:02:359 cheats.cpp:502 N[COMMON]: Applying widescreen hack to game MK-51000
00:02:359 emulator.cpp:54 N[BOOT]: Game ID is [MK-51000]
00:02:419 audio/audiobackend_oboe.cpp:121 N[AUDIO]: Oboe driver started. stream capacity: 1418 frames, size: 1418 frames, frames/callback: 512, frames/burst: 472
00:02:419 reios/reios.cpp:622 N[REIOS]: -----------------
00:02:419 reios/reios.cpp:623 N[REIOS]: REIOS: Booting up
00:02:419 reios/reios.cpp:624 N[REIOS]: -----------------
00:03:142 audio/audiobackend_oboe.cpp:128 N[AUDIO]: Oboe driver stopping
00:04:279 nullDC.cpp:222 N[SAVESTATE]: Loaded state ver 843 from /storage/emulated/0/Download/Flycast/data/Sonic Adventure v1.005 (1999)(Sega)(NTSC)(US)(M5)[!][24S 51000A].state size 28085459
00:04:314 audio/audiobackend_oboe.cpp:121 N[AUDIO]: Oboe driver started. stream capacity: 2836 frames, size: 2836 frames, frames/callback: 512, frames/burst: 882
00:45:033 audio/audiobackend_oboe.cpp:128 N[AUDIO]: Oboe driver stopping

**_Screenshots_**

![Screenshot_20240306-160755](https://github.com/flyinghead/flycast/assets/162517062/ea2de15f-036d-41e5-91b3-16fa32bfe758)

**Comment by flyinghead** [comment] 2024-03-07 07:56
Per pixel sorting is quite demanding is requires a fast GPU and good Vulkan driver. If your phone is too slow there isn't much that can be done.

Otherwise this is a duplicate of #100.

**Closed** 2024-03-17 21:49 UTC
