### ISSUE TITLE
(Android)(Scoop Storage) Flycast data file directory always reset when app is clear/killed.

### ISSUE THREAD

**Issue by Gamemulatorer** [flyinghead/flycast#314] opened 2021-08-12 04:38 UTC
**Please Note: This form is the minimum required information for submitting bugs.**  
**Removing this form may lead to your issue being closed until it is completed.**

### Platform/OS/Hardware: 
Android 11 MIUI 12.5.1 Mediatek Helio G85

### Github Hash
fcef404f

### Screen Record
[Screenrecorder-2021-08-12-12-37-01-297.mp4.zip](https://github.com/flyinghead/flycast/files/6972863/Screenrecorder-2021-08-12-12-37-01-297.mp4.zip)

**Comment by flyinghead** [comment] 2021-08-12 06:13
Your data directory is incorrect: `:/`
So the configuration file cannot be saved and the settings are reset when the app is killed.

The real issue is how this invalid data directory was set. When you start the app for the first time (or after deinstall/reinstall), it asks the user to specify the data directory. At this point something happened and a wrong directory was selected.

Could it be a consequence of scoped storage permissions in Android 11 that you had previously (#286)? Can you try to reproduce this issue by desinstalling/resintalling the app?

**Comment by Gamemulatorer** [comment] 2021-08-12 07:25
I uninstall and reinstall and tried the latest version available on https://flyinghead.github.io/flycast-builds/
![Screenshot_2021-08-12-14-47-49-140_com google android permissioncontroller](https://user-images.githubusercontent.com/37603562/129155329-5ef9c251-04d9-43a5-893c-cbc56db0d881.jpg)
![Screenshot_2021-08-12-14-48-06-444_com flycast emulator](https://user-images.githubusercontent.com/37603562/129155337-733e738a-c689-4afb-a788-033732e21a81.jpg)
It's now fixed!!!

**Comment by Gamemulatorer** [comment] 2021-08-30 12:34
The latest version still have this issue after the app is killed on recent can only reproduce 2X or more.
![Screenshot_2021-08-30-20-32-50-520_com flycast emulator](https://user-images.githubusercontent.com/37603562/131339628-8b729e27-3f92-4677-9b7e-9efdfc22ac98.jpg)

**Comment by Gamemulatorer** [comment] 2021-08-31 17:33
The label should be change to bug and not question.

**Comment by flyinghead** [comment] 2021-08-31 17:42
I can't reproduce the bug with Android 11. When first installed it asks for permission to access external storage and if the permission is granted, no problem happens. You said it was fixed by reinstalling the app but there hasn't been any change in the code.

Please give me precise steps to reproduce the issue.

**Comment by Gamemulatorer** [comment] 2021-09-01 00:15
My DC folder is located on my external storage

**Comment by Gamemulatorer** [comment] 2021-09-02 07:07
To reproduce open flycast > settings > add content location > done > exit flyacst > open again then boom content location is gone back to zero.

**Comment by Gamemulatorer** [comment] 2021-09-02 07:08
```
[09-02 15:04:38.047 1374:8687 D/PackageManager]
android.permission.READ_EXTERNAL_STORAGE is granted, packageName: com.flycast.emulator, callingUid: 10084, userId: 0

[09-02 15:04:38.047 1374:8687 I/sysui_multi_action]
[757,1243,758,4,806,com.flycast.emulator,1241,android.permission.READ_EXTERNAL_STORAGE]

[09-02 15:04:38.056 1374:8687 D/PackageManager]
android.permission.WRITE_EXTERNAL_STORAGE is granted, packageName: com.flycast.emulator, callingUid: 10084, userId: 0

[09-02 15:04:38.056 1374:8687 I/sysui_multi_action]
[757,1243,758,4,806,com.flycast.emulator,1241,android.permission.WRITE_EXTERNAL_STORAGE]

[09-02 15:04:38.065 1374:3058 D/PackageManager]
android.permission.READ_EXTERNAL_STORAGE is granted, packageName: com.flycast.emulator, callingUid: 10084, userId: 0

[09-02 15:04:38.065 1374:3058 I/sysui_multi_action]
[757,1243,758,4,806,com.flycast.emulator,1241,android.permission.READ_EXTERNAL_STORAGE]

[09-02 15:04:38.069 1374:3061 D/PackageManager]
android.permission.WRITE_EXTERNAL_STORAGE is granted, packageName: com.flycast.emulator, callingUid: 10084, userId: 0

[09-02 15:04:38.070 1374:3061 I/sysui_multi_action]
[757,1243,758,4,806,com.flycast.emulator,1241,android.permission.WRITE_EXTERNAL_STORAGE]

[09-02 15:04:38.089 1374:3058 D/PackageManager]
android.permission.READ_EXTERNAL_STORAGE is granted, packageName: com.flycast.emulator, callingUid: 10084, userId: 0

[09-02 15:04:38.089 1374:3058 I/sysui_multi_action]
[757,1243,758,4,806,com.flycast.emulator,1241,android.permission.READ_EXTERNAL_STORAGE]

[09-02 15:04:38.094 1374:1394 I/Timeline]
Timeline: Activity_windows_visible id: ActivityRecord{9f7ff45 u0 com.flycast.emulator/com.reicast.emulator.MainActivity t535} time:78282381

[09-02 15:04:38.096 1374:8687 D/PackageManager]
android.permission.WRITE_EXTERNAL_STORAGE is granted, packageName: com.flycast.emulator, callingUid: 10084, userId: 0

[09-02 15:04:38.096 1374:8687 I/sysui_multi_action]
[757,1243,758,4,806,com.flycast.emulator,1241,android.permission.WRITE_EXTERNAL_STORAGE]

[09-02 15:04:38.130 9646:9646 I/snet_event_log]
[individual_permissions_requested,10500,com.flycast.emulator:;android.permission.READ_EXTERNAL_STORAGE|true|11009;android.permission.WRITE_EXTERNAL_STORAGE|true|11009]

[09-02 15:04:38.137 1374:3059 W/WindowManager]
Changing focus fromnull to Window{78ab6c8 mode=1 rootTaskId=535 u0 com.flycast.emulator/com.reicast.emulator.MainActivity} displayId=0 Callers=com.android.server.wm.RootWindowContainer.updateFocusedWindowLocked:469 com.android.server.wm.WindowManagerService.updateFocusedWindowLocked:6048 com.android.server.wm.DisplayContent.setFocusedApp:5749 com.android.server.wm.ActivityTaskManagerService.setResumedActivityUncheckLocked:5716 

[09-02 15:04:38.139 1374:3059 D/WindowManager]
Input focus has changed to Window{78ab6c8 mode=1 rootTaskId=535 u0 com.flycast.emulator/com.reicast.emulator.MainActivity}

[09-02 15:04:38.139 1374:3059 I/wm_set_resumed_activity]
[0,com.flycast.emulator/com.reicast.emulator.MainActivity,resumeTopActivityInnerLocked]

[09-02 15:04:38.254 1374:3059 I/wm_resume_activity]
[0,167247685,535,com.flycast.emulator/com.reicast.emulator.MainActivity]

[09-02 15:04:38.267 1374:3059 V/WindowManager]
Orientation start waiting for draw, mDrawState=DRAW_PENDING in Window{28cbcee mode=1 rootTaskId=535 u0 Splash Screen com.flycast.emulator EXITING}, surfaceController Surface(name=Splash Screen com.flycast.emulator)/@0x4fcc523

[09-02 15:04:38.267 1374:3059 V/WindowManager]
Orientation start waiting for draw, mDrawState=DRAW_PENDING in Window{78ab6c8 mode=1 rootTaskId=535 u0 com.flycast.emulator/com.reicast.emulator.MainActivity}, surfaceController Surface(name=com.flycast.emulator/com.reicast.emulator.MainActivity)/@0x9fa4347

[09-02 15:04:38.355 1374:1394 I/Timeline]
Timeline: Activity_windows_visible id: ActivityRecord{9f7ff45 u0 com.flycast.emulator/com.reicast.emulator.MainActivity t535} time:78282642
```

**Comment by Gamemulatorer** [comment] 2021-09-02 07:34
> I can't reproduce the bug with Android 11. When first installed it asks for permission to access external storage and if the permission is granted, no problem happens. You said it was fixed by reinstalling the app but there hasn't been any change in the code.

Im sorry but I only test it once, twice but seems the issue still can reproduce flycast still have a issue on android 11 external storage.

**Comment by flyinghead** [comment] 2021-09-02 16:56
I did some tests again on a Pixel 3 Android 11.
At startup, I can select a home directory on internal storage or on an external SD Card. In both cases Flycast can read and write the directory without issue. The configuration is retained even after killing the app.
![image](https://user-images.githubusercontent.com/16261910/131885583-dac72e09-65a1-4afb-83cf-cb17dfba03a8.png)

I did some tests to support Android 11 scoped storage but this is just insane: Flycast can't even *read* any storage...

**Comment by Gamemulatorer** [comment] 2021-09-03 10:25
This is sad I can't enjoy playing with flycast content location is always reset on my phone :/
![Screenshot_2021-09-03-18-23-24-120_com flycast emulator](https://user-images.githubusercontent.com/37603562/131990801-6e60de23-3978-4220-8407-c458604473d2.jpg)
Even on my internal storage when I select it as content location is alway reset :/

**Comment by Gamemulatorer** [comment] 2021-09-07 18:19
Seems ok now after playing for a couple of minutes 😅

**Closed** 2021-09-09 04:58 UTC
Labels: question

**Comment by flyinghead** [comment] 2021-09-09 16:18
Do you know how you fixed it? Anything I can do on the emulator side?

**Comment by Gamemulatorer** [comment] 2021-09-09 17:01
After playing ang saving game progress this issue is totally gone 😄
