### ISSUE TITLE
Uneven FPS Limiter

### ISSUE THREAD

**Issue by Ichisich** [flyinghead/flycast#1087] opened 2023-05-26 17:30 UTC
FlyCast's fps limiter seems to produce very uneven frametimes, especially with 30fps games.
Setting an external fps limit via RTSS and disabling the native limiter with turbo mode (Space) eliminates the issue completely.

A good scene, as the movement is static and easy to reproduce, is the menu in Star Wars Racer.
The judder is easily recognizable when it comes to the planet rotation and moon orbits.

Native 30 fps limit:
https://github.com/flyinghead/flycast/assets/31080003/2ecc8235-778a-4e40-89a1-343d9daaa92f

RTSS 30 fps limit:
https://github.com/flyinghead/flycast/assets/31080003/706c3f81-975d-4bda-8bfd-83df8f8711d6

In case you haven't an eye for this kind of issues.
Slowing down the video makes it blatant.

Native gives the appearance the moon dances a waltz:
https://github.com/flyinghead/flycast/assets/31080003/5d0df5b6-0700-44b0-b1f7-e07523d41cc2

With RTSS the moon moves exactly one step a frame:
https://github.com/flyinghead/flycast/assets/31080003/c18108f1-4e91-445d-9f6c-4aa05cd7d033

The video is recorded with the default settings, but I also tested different setups vsync on/off, delay frame swapping on/off and all graphic API, but the result is always identical.

P.S.
Is there an option to disable the frame limiter without disabling sound, as a temporary workaround?

**Comment by flyinghead** [comment] 2023-05-26 18:19
This happens because flycast renders at the same frame rate as the game, which doesn't work well for 30 fps games on 60+ Hz monitors. See issues #1022 and #1083.

One solution is to enable Full Framebuffer Emulation, which will output 60 FPS with all games but imposes some limitations.

Another possible future enhancement is to duplicate frames. See issue #520.

**Comment by Ichisich** [comment] 2023-05-26 19:48
Thanks for your quick reply, and Full Framebuffer Emulation is a sufficient workaround.
My question still stands, is there a way to disable the limiter without disabling audio?

BTT:.
Duplicate frames could solve it, but I tested some 60fps constellations, and it seems the reason 60fps doesn't show this erratic behavior **_constantly_** is because vsync applies just before the limiter can most of the time.

Disabling vsync, so the limiter always applies, results in the same framepacing issues as with 30fps.
Now I'm pretty convinced that the limiter is the sole culprit and when it comes to 30fps the limiter just always applies just before vsync can.
Probably because the delta between ntsc and 60fps is bigger, than with ntsc/2 and 30fps.

1. Duplicate frames would only shift the issue and not solve it.
2. Half refresh rate vsync would only work with 60Hz and not Freesync/Gsync monitors
3. Implementing a new limiter is probably no small feat.

**Comment by Ichisich** [comment] 2023-05-27 08:25
I run a test into freesync, so the limiter always applies, with a 60fps title to get it 100% confirmed.

60fps with native limiter:
https://github.com/flyinghead/flycast/assets/31080003/b509f059-83fd-4aa3-a4b9-6521bd8ad366

60fps with rtss limiter:
https://github.com/flyinghead/flycast/assets/31080003/de084ec4-2852-4e95-877a-af2c00ed5775

Frame duplication would only solve the issue coincidentally when using a 60Hz monitor, which are getting increasingly rarer, and enabling vsync.

**Comment by RiasatSalminSami** [comment] 2023-07-22 08:41
Full Framebuffer Emulation removes the ability for increasing rendering resolution. So it's not a great solution in my opinion. A better workaround for the framepacing and frame duplication should be made.   Capping to 30 FPS via external methods works to some extent but games that have 60 fps in menus become 2x slower because of this external cap. This is not really ideal either.

**Comment by Ichisich** [comment] 2023-07-22 12:24
The only solution, without any drawbacks, would be to implement a better internal frame limiter.

**Comment by Immersion95** [comment] 2023-09-16 21:42
Same issue with freesync/vrr here, the frame limiter isn't tight enough and produce judder. Other emulators with 30fps doesn't cause any issue.

**Comment by flyinghead** [comment] 2023-10-14 16:39
Duplicate of #520.

**Closed by flyinghead** 2023-10-14 16:39 UTC
Labels: bug, duplicate
